Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2020-12, with the labels that each got.

#525 Tags update for multi-material crafting recipes
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/dusts.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/gears.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ingots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/nuggets.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
Labels: Enhancement

#527 Recipe Updates
  kubejs/client_scripts/item_modifiers/jei_hide.js
  kubejs/data/immersiveengineering/recipes/crafting/insulating_glass.json
  kubejs/data/industrialforegoing/recipes/animal_baby_separator.json
  kubejs/data/industrialforegoing/recipes/animal_feeder.json
  kubejs/data/industrialforegoing/recipes/animal_rancher.json
  kubejs/data/industrialforegoing/recipes/biofuel_generator.json
  kubejs/data/industrialforegoing/recipes/block_breaker.json
  kubejs/data/industrialforegoing/recipes/conveyor.json
  kubejs/data/industrialforegoing/recipes/conveyor_blinking_upgrade.json
  kubejs/data/industrialforegoing/recipes/conveyor_bouncing_upgrade.json
  kubejs/data/industrialforegoing/recipes/conveyor_detection_upgrade.json
  kubejs/data/industrialforegoing/recipes/conveyor_dropping_upgrade.json
  kubejs/data/industrialforegoing/recipes/conveyor_extraction_upgrade.json
  kubejs/data/industrialforegoing/recipes/conveyor_insertion_upgrade.json
  kubejs/data/industrialforegoing/recipes/conveyor_splitting_upgrade.json
  kubejs/data/industrialforegoing/recipes/dissolution_chamber.json
  kubejs/data/industrialforegoing/recipes/dye_mixer.json
  kubejs/data/industrialforegoing/recipes/fluid_collector.json
  kubejs/data/industrialforegoing/recipes/fluid_extractor.json
  kubejs/data/industrialforegoing/recipes/fluid_placer.json
  kubejs/data/industrialforegoing/recipes/laser_drill.json
  kubejs/data/industrialforegoing/recipes/latex_processing_unit.json
  kubejs/data/industrialforegoing/recipes/machine_frame_pity.json
  kubejs/data/industrialforegoing/recipes/marine_fisher.json
  kubejs/data/industrialforegoing/recipes/material_stonework_factory.json
  kubejs/data/industrialforegoing/recipes/meat_feeder.json
  kubejs/data/industrialforegoing/recipes/mob_crusher.json
  kubejs/data/industrialforegoing/recipes/mob_slaughter_factory.json
  kubejs/data/industrialforegoing/recipes/plant_fertilizer.json
  kubejs/data/industrialforegoing/recipes/plant_gatherer.json
  kubejs/data/industrialforegoing/recipes/plant_sower.json
  kubejs/data/industrialforegoing/recipes/resourceful_furnace.json
  kubejs/data/industrialforegoing/recipes/sewage_composter.json
  kubejs/data/industrialforegoing/recipes/sewer.json
  kubejs/data/industrialforegoing/recipes/sludge_refiner.json
  kubejs/data/industrialforegoing/recipes/spores_recreator.json
  kubejs/data/industrialforegoing/recipes/stasis_chamber.json
  kubejs/data/industrialforegoing/recipes/water_condensator.json
  kubejs/data/mekanism/recipes/energy_cube/elite.json
  kubejs/data/mekanism/recipes/factory/elite/combining.json
  kubejs/data/mekanism/recipes/factory/elite/compressing.json
  kubejs/data/mekanism/recipes/factory/elite/crushing.json
  kubejs/data/mekanism/recipes/factory/elite/enriching.json
  kubejs/data/mekanism/recipes/factory/elite/infusing.json
  kubejs/data/mekanism/recipes/factory/elite/injecting.json
  kubejs/data/mekanism/recipes/factory/elite/purifying.json
  kubejs/data/mekanism/recipes/factory/elite/sawing.json
  kubejs/data/mekanism/recipes/factory/elite/smelting.json
  kubejs/data/mekanism/recipes/fluid_tank/advanced.json
  kubejs/data/mekanism/recipes/fluid_tank/basic.json
  kubejs/data/mekanism/recipes/fluid_tank/elite.json
  kubejs/data/mekanism/recipes/fluid_tank/ultimate.json
  kubejs/data/pneumaticcraft/recipes/minigun.json
  kubejs/data/rftoolsstorage/recipes/storage_module0.json
  kubejs/data/rftoolsstorage/recipes/storage_module1.json
  kubejs/data/rftoolsstorage/recipes/storage_module2.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/pressure_chamber.js
Labels: Enhancement

#550 Rods and Wires - Just for Fun
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/press.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/wires.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/thermal/dies.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/additions.js
Labels: Enhancement

#556 Crushing Update
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling_rods.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crusher.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/byg.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching_byg_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing_rods.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge_flowers.js
Labels: Enhancement

#575 Building Gadgets Schematics
  building_gadgets_patterns/astral_sorcery/astral_relay.txt
  building_gadgets_patterns/astral_sorcery/attunement_altar.txt
  building_gadgets_patterns/astral_sorcery/crafting_celestial_altar.txt
  building_gadgets_patterns/astral_sorcery/crafting_iridescent_altar.txt
  building_gadgets_patterns/astral_sorcery/crafting_starlight_altar.txt
  building_gadgets_patterns/astral_sorcery/enhanced_celestial_collector_crystal.txt
  building_gadgets_patterns/astral_sorcery/evershifting_fountain.txt
  building_gadgets_patterns/astral_sorcery/ritual_pedestal.txt
  building_gadgets_patterns/immersive_engineering/arc_furnace.txt
  building_gadgets_patterns/immersive_engineering/assembler.txt
  building_gadgets_patterns/immersive_engineering/automated_engineers_workbench.txt
  building_gadgets_patterns/immersive_engineering/bottling_machine.txt
  building_gadgets_patterns/immersive_engineering/crusher.txt
  building_gadgets_patterns/immersive_engineering/diesel_generator.txt
  building_gadgets_patterns/immersive_engineering/excavator.txt
  building_gadgets_patterns/immersive_engineering/fermentor.txt
  building_gadgets_patterns/immersive_engineering/improved_blast_furnace.txt
  building_gadgets_patterns/immersive_engineering/lightning_rod.txt
  building_gadgets_patterns/immersive_engineering/metal_press.txt
  building_gadgets_patterns/immersive_engineering/mixer.txt
  building_gadgets_patterns/immersive_engineering/refinery.txt
  building_gadgets_patterns/immersive_engineering/sawmill.txt
  building_gadgets_patterns/immersive_engineering/silo.txt
  building_gadgets_patterns/immersive_engineering/squeezer.txt
  building_gadgets_patterns/immersive_engineering/tank.txt
  building_gadgets_patterns/immersive_petroleum/distillation_tower.txt
  building_gadgets_patterns/immersive_petroleum/pumpjack.txt
  building_gadgets_patterns/mekanism/basic_fission_reactor.txt
  building_gadgets_patterns/mekanism/basic_fusion_reactor.txt
  building_gadgets_patterns/mekanism/basic_industrial_turbine.txt
  building_gadgets_patterns/mekanism/basic_sps.txt
  building_gadgets_patterns/mekanism/basic_thermal_evap_tower.txt
  building_gadgets_patterns/natures_aura/altar_of_birthing.txt
  building_gadgets_patterns/natures_aura/crimson_altar.txt
  building_gadgets_patterns/natures_aura/natural_altar.txt
Labels: Enhancement

#595 Update to 0.3.2, pre-changelogs
  config/Mekanism/tools.toml
  config/quark-common.toml
  config/resourcefulbees/bees/Wither.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/cherry.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/dead.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/fir.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/hellbark.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/jacaranda.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/magic.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/mahogany.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/palm.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/redwood.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/umbran.json
  kubejs/data/mekanism/recipes/compat/biomesoplenty/sawing/log/willow.json
  kubejs/data/mekanism/recipes/sawing/planks.json
  kubejs/data/mekanism/recipes/sawing/slabs.json
  kubejs/data/mekanism/recipes/sawing/stairs.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/tool_shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/sawmill.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/insolator_simplefarming_trees.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/sawmill.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/additions.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
  kubejs/server_scripts/enigmatica/kubejs/functions.js
  kubejs/server_scripts/enigmatica/kubejs/global_constants.js
  kubejs/startup_scripts/factory/items.js
  minecraftinstance.json
Labels: Maintenance

#596 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.2.txt
  settings.ps1
Labels: Maintenance

#608 Update compression.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/compression.js
Labels: Bug

#673 More quest related tags
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/astralsorcery/astralsorcery.js
Labels: Enhancement, Quest
