Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-09, with the labels that each got.

#3147 [Expert] Further Magical integrations, beginnings of Digital Storage
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  kubejs/assets/enigmatica/lang/en_us.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/dimensional_storage_crystal.png
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/arc.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/sawmill.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3154 Update trees/growables with new BetterEnd items. Add Chipped blocks to Stonecutter
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: Enhancement

#3155 [Expert] Finishing out disks and processor proposal
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/press.js
Labels: Development

#3156 Ars Nouveau Quest refresh: New info on minions and new spell practice quest
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Enhancement

#3163 refreshed ars config, and re-added dim blacklist, ee gems and no hunting passives for wilden mobs
  config/ars_nouveau-common.toml
Labels: Maintenance

#3165 [Expert] Update theme to BM recipes, expertify ore processing, and more
  config/naturesaura-common.toml
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/bloodmagic/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Development

#3169 Fix missing NBT on SushiGo Wasabee outputs
  config/resourcefulbees/bees/special/Wasabee.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/shaped.js
Labels: Bug

#3170 Refactor Base Shaped Crafting recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botanypots/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/byg/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/cfm/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/decorative_blocks/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/engineersdecor/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/farmersdelight/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/fluxnetworks/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ppfluids/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/prettypipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/rftoolscontrol/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/simplefarming/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/supplementaries/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/undergarden/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/upgrade_aquatic/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/prettypipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/prettypipes/shaped.js
Labels: Development

#3177 Add Routing Nodes to BM Quests, Add Alt materials for new Ars and BM items
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
Labels: Enhancement

#3179 [Expert] Sourcelink update
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/shaped.js
Labels: Development

#3183 [Expert] Major starmetal change, More work on magical themes
  config/configswapper/expert/astralsorcery.txt
  config/configswapper/normal/astralsorcery.txt
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/block_transmutation.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/glyph_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/block_transmutation.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/betterend/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/items/pneumaticcraft/upgrade_components.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/astralsorcery/block_transmutation.js
Labels: Development

#3190 Remove Starmetal dupe loop from smeltery
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Bug

#3191 Cobblegen and Stonegen Ponders
  config/byg/byg-world.toml
  kubejs/assets/enigmatica/ponder/enigmatica/cobbleworks/random_cobblegen.nbt
  kubejs/assets/enigmatica/ponder/enigmatica/cobbleworks/targeted_cobblegen.nbt
  kubejs/assets/enigmatica/ponder/enigmatica/cobbleworks/vanilla_cobblegen.nbt
  kubejs/assets/enigmatica/ponder/enigmatica/stoneworks/random_stonegen.nbt
  kubejs/assets/enigmatica/ponder/enigmatica/stoneworks/targeted_stonegen.nbt
  kubejs/assets/enigmatica/ponder/enigmatica/stoneworks/vanilla_stonegen.nbt
  kubejs/client_scripts/ponder/base.js
  kubejs/client_scripts/ponder/enigmatica/cobbleworks.js
  kubejs/client_scripts/ponder/enigmatica/stoneworks.js
Labels: Enhancement

#3196 Set hidden storage quest to optional
  config/ftbquests/quests/chapters/storage.snbt
Labels: Bug

#3197 [Expert + Normal] Occultism Ritual update
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/cephalopods.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/thrashers.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/forge/villagers.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/forge/zombies.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/occultism/wild_hunt_sacrifices.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Development

#3199 Pondering Portals
  kubejs/assets/enigmatica/ponder/portals/atum/portal.nbt
  kubejs/assets/enigmatica/ponder/portals/undergarden/portal.nbt
  kubejs/client_scripts/ponder/base.js
  kubejs/client_scripts/ponder/portals/atum.js
  kubejs/client_scripts/ponder/portals/undergarden.js
Labels: Enhancement

#3200 Add Crucible Melting and Blast Chiller Recipe Compat
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/chiller.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/crucible.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Enhancement

#3201 Update Adventure Quests to call out the new Ponders!
  config/ftbquests/quests/chapters/adventure.snbt
Labels: Enhancement

#3206 [Expert] Rune re-shuffling and other tweaks
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#3209 [Expert] Botania Flora Update
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/petal_apothecary.js
Labels: Development

#3212 [Expert] Concrete Curing
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/block_heat_properties.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/heat_frame_cooling.js
Labels: Development

#3217 Missing assembly recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
Labels: Development

#3233 [Expert] Powah Integration - First pass
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/pentacle.png
  kubejs/assets/kubejs/textures/item/spirit_heat_exchanger.png
  kubejs/assets/kubejs/textures/item/spirit_heat_exchanger.png.mcmeta
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/pressing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/metal_press.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pedestals/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/press.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/powah/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3240 [Expert] recipe tweaks
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
Labels: Development

#3242 [Expert] Adds tooltips to some custom summons and move Sentient tools to rituals
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/items/atum/nebu_hammer.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/items/occultism/occultism_spirit_tooltip.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3249 Intermediate Cutting Fluid now requires water bottle instead of any potion bottle
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
Labels: Enhancement

#3250 Remove secondary marble slab recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#3241 Add Ender Dragon Respawn & Tetra Forge Hammer Ponders
  kubejs/assets/enigmatica/ponder/enigmatica/ender_dragon/end_portal.nbt
  kubejs/assets/enigmatica/ponder/tetra/forge_hammer/forge_hammer.nbt
  kubejs/client_scripts/ponder/base.js
  kubejs/client_scripts/ponder/enigmatica/cobbleworks.js
  kubejs/client_scripts/ponder/enigmatica/end_dragon_respawn.js
  kubejs/client_scripts/ponder/enigmatica/forge_hammer.js
  kubejs/client_scripts/ponder/enigmatica/stoneworks.js
  kubejs/client_scripts/ponder/industrial_foregoing/laser_drill.js
  kubejs/client_scripts/ponder/industrial_foregoing/latex.js
  kubejs/client_scripts/ponder/portals/atum.js
  kubejs/client_scripts/ponder/portals/undergarden.js
Labels: Enhancement

#3254 Add "Tier" indicator to Bee Lore
  config/resourcefulbees/bees/alloy/Brass.json
  config/resourcefulbees/bees/alloy/Bronze.json
  config/resourcefulbees/bees/alloy/Constantan.json
  config/resourcefulbees/bees/alloy/Electrum.json
  config/resourcefulbees/bees/alloy/Enderium.json
  config/resourcefulbees/bees/alloy/Invar.json
  config/resourcefulbees/bees/alloy/Lumium.json
  config/resourcefulbees/bees/alloy/Signalum.json
  config/resourcefulbees/bees/alloy/Steel.json
  config/resourcefulbees/bees/gem/Diamond.json
  config/resourcefulbees/bees/gem/Emerald.json
  config/resourcefulbees/bees/gem/Lapis.json
  config/resourcefulbees/bees/gem/Redstone.json
  config/resourcefulbees/bees/material/Clay.json
  config/resourcefulbees/bees/material/Gravel.json
  config/resourcefulbees/bees/metal/Aluminum.json
  config/resourcefulbees/bees/metal/Copper.json
  config/resourcefulbees/bees/metal/Gold.json
  config/resourcefulbees/bees/metal/Iron.json
  config/resourcefulbees/bees/metal/Lead.json
  config/resourcefulbees/bees/metal/Nickel.json
  config/resourcefulbees/bees/metal/Osmium.json
  config/resourcefulbees/bees/metal/Silver.json
  config/resourcefulbees/bees/metal/Tin.json
  config/resourcefulbees/bees/metal/Uranium.json
  config/resourcefulbees/bees/metal/Zinc.json
  config/resourcefulbees/bees/natural/Coal.json
  config/resourcefulbees/bees/natural/Creeper.json
  config/resourcefulbees/bees/natural/Ender.json
  config/resourcefulbees/bees/natural/Forest.json
  config/resourcefulbees/bees/natural/Glowstone.json
  config/resourcefulbees/bees/natural/Icy.json
  config/resourcefulbees/bees/natural/Obsidian.json
  config/resourcefulbees/bees/natural/Pigman.json
  config/resourcefulbees/bees/natural/RGBee.json
  config/resourcefulbees/bees/natural/Rocky.json
  config/resourcefulbees/bees/natural/Sand.json
  config/resourcefulbees/bees/natural/Skeleton.json
  config/resourcefulbees/bees/natural/Slimy.json
  config/resourcefulbees/bees/natural/Water.json
  config/resourcefulbees/bees/natural/Zombie.json
  config/resourcefulbees/bees/nether/Blaze.json
  config/resourcefulbees/bees/nether/Ghast.json
  config/resourcefulbees/bees/nether/Netherite.json
  config/resourcefulbees/bees/nether/Wither.json
  config/resourcefulbees/bees/nether/nether_quartz.json
Labels: Maintenance

#3256 Remove powah cables from quest rewards
  config/ftbquests/quests/chapters/powah.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  kubejs/data/enigmatica/loot_tables/chests/quest_powah_loot.json
Labels: Development

#3257 fixing typos
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/energizing.js
Labels: Development

#3258 Fix Quartz Enriched Iron
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/shapeless.js
Labels: Development

#3259 Fixes Minor typo in PNC quests
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
Labels: Enhancement

#3266 Nori Sheet Ponder
  kubejs/assets/enigmatica/ponder/enigmatica/bases/3x3.nbt
  kubejs/assets/enigmatica/ponder/sushigocrafting/nori_sheets/nori_press.nbt
  kubejs/assets/enigmatica/ponder/sushigocrafting/nori_sheets/seaweed.nbt
  kubejs/client_scripts/ponder/base.js
  kubejs/client_scripts/ponder/tech/industrialforegoing/laser_drill.js
  kubejs/client_scripts/ponder/tech/industrialforegoing/latex.js
  kubejs/client_scripts/ponder/tech/sushigocrafting/nori_sheets.js
  kubejs/client_scripts/ponder/tools/forge_hammer.js
Labels: Enhancement

#3272 Allow ftb ultimine to harvest entire menril tree (excl. leaves)
  defaultconfigs/ftbultimine-server.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/ftbultimine/menril_logs.js
Labels: Enhancement

#3275 Allow ftb ultimine to harvest entire menril tree (excl. leaves) Credit: Quezler
  defaultconfigs/ftbultimine-server.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/ftbultimine/menril_logs.js
Labels: Enhancement

#3277 Blacklist Sophisticated Backpacks from Equipment Compare
  defaultconfigs/equipmentcompare-common.toml
Labels: Development

#3281 [Expert] Better Nautilus Yields
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/farmersdelight/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/crushing.js
Labels: Development

#3280 Hive Upgrade Type/Tier Recipes
  kubejs/assets/enigmatica/ponder/resourcefulbees/mutation/mutation_chamber.nbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/hive_upgrade_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/resourcefulbees/hive_upgrade_recipe.js
Labels: Enhancement

#3284 Fix to known_stages
  config/gamestages/known_stages.json
Labels: Development

#3286 [Expert] PneumaticCraft Expertification
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/expert/item_modifiers/jei_hide_items.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/block_heat_properties.js
  kubejs/server_scripts/enigmatica/kubejs/expert/block/loot_tables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/block_heat_properties.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/resourcefulbees/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/supplementaries/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/bottler.js
Labels: Development

#3294 [Expert] Mineral Survey Drones
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/amadron_survey_tools.png
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/amadron_survey_loot_tables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/amadron.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3297 [Expert] PNC Tweaks
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
Labels: Development

#3299 Adds survey kits that can be traded to Amadron for resources!
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/amadron.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/amadron.js
Labels: Enhancement

#3304 Refactor mob spawning blacklists
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/drygmy_blacklist.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/mob_imprisonment_tool_blacklist.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/ars_nouveau/drygmy_blacklist.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/mob_spawner_blacklist.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/industrialforegoing/mob_imprisonment_tool_blacklist.js
Labels: Development

#3308 RBees Mutation Ponder
  kubejs/assets/enigmatica/ponder/resourcefulbees/mutation/mutation_chamber.nbt
  kubejs/client_scripts/ponder/base.js
  kubejs/client_scripts/ponder/magic/resourcefulbees/mutation.js
Labels: Enhancement

#3319 PVJ Tree Compat
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: Development

#3321 0.5.14
  automation/settings.ps1
  config/chiselsandbits-common.toml
  config/ftbquests/quests/chapters/tech_t3.snbt
  config/terraforged/biome_weights.conf
  kubejs/assets/ponderjs/lang/en_us.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/projectvibrantjourneys_saplings.json
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
  minecraftinstance.json
Labels: Development

#3324 remove extra Expert amadron recipe, add dimensional matrix tag to simplifiy autocrafting
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/occultism/dimensional_matrix.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
Labels: Maintenance

#3327 Change Artifact Infinity Tools to accept Weak NBT instead of Strong
  config/ftbquests/quests/chapters/challenges.snbt
Labels: Enhancement

#3328 [Expert] Occultism and Ars Nouveau tweaks
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/dropbears.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/rattlesnakes.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Development

#3332 Hide disabled trinkets in JEI
  kubejs/client_scripts/constants.js
Labels: Maintenance

#3341 Make Morph o Tool work with Compact Machine Shrink Device
  config/morphtool-common.toml
Labels: Enhancement

#3335 [Expert] Blood Magic Updates
  config/configswapper/expert/occultism.txt
  config/configswapper/normal/occultism.txt
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/bloodmagic/alchemytable.js
Labels: Development
