Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-03, with the labels that each got.

#1495 Occultism Wither Summon: Change Loot Table to Armor and Weapon drops instead of Apoth targeted books
  kubejs/data/occultism/loot_tables/entities/wild_hunt_wither_skeleton.json
Labels: Enhancement

#1503 Changelogs and a few dev fixes
  .gitignore
  MODLIST.md
  ModpackUploader.ps1
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.2.md
  config/ftbchunks-client.toml
  github-changelog-generator.bat
Labels: Maintenance

#1504 Imgbot
  kubejs/assets/ironchest/textures/item/copper_iron_upgrade.png
  kubejs/assets/ironchest/textures/item/copper_silver_upgrade.png
  kubejs/assets/ironchest/textures/item/diamond_crystal_upgrade.png
  kubejs/assets/ironchest/textures/item/diamond_obsidian_upgrade.png
  kubejs/assets/ironchest/textures/item/gold_diamond_upgrade.png
  kubejs/assets/ironchest/textures/item/iron_gold_upgrade.png
  kubejs/assets/ironchest/textures/item/silver_gold_upgrade.png
  kubejs/assets/ironchest/textures/item/wood_copper_upgrade.png
  kubejs/assets/ironchest/textures/item/wood_iron_upgrade.png
  kubejs/assets/ironchest/textures/model/copper_chest.png
  kubejs/assets/ironchest/textures/model/crystal_chest.png
  kubejs/assets/ironchest/textures/model/diamond_chest.png
  kubejs/assets/ironchest/textures/model/gold_chest.png
  kubejs/assets/ironchest/textures/model/iron_chest.png
  kubejs/assets/ironchest/textures/model/obsidian_chest.png
  kubejs/assets/ironchest/textures/model/silver_chest.png
  kubejs/assets/mekanism/textures/block/bin/advanced_front.png
  kubejs/assets/mekanism/textures/block/bin/advanced_front_on.png
  kubejs/assets/mekanism/textures/block/bin/advanced_side.png
  kubejs/assets/mekanism/textures/block/bin/advanced_side_on.png
  kubejs/assets/mekanism/textures/block/bin/advanced_top.png
  kubejs/assets/mekanism/textures/block/bin/advanced_top_on.png
  kubejs/assets/mekanism/textures/block/bin/basic_front.png
  kubejs/assets/mekanism/textures/block/bin/basic_front_on.png
  kubejs/assets/mekanism/textures/block/bin/basic_side.png
  kubejs/assets/mekanism/textures/block/bin/basic_side_on.png
  kubejs/assets/mekanism/textures/block/bin/basic_top.png
  kubejs/assets/mekanism/textures/block/bin/basic_top_on.png
  kubejs/assets/mekanism/textures/block/bin/bottom.png
  kubejs/assets/mekanism/textures/block/bin/creative_front.png
  kubejs/assets/mekanism/textures/block/bin/creative_front_on.png
  kubejs/assets/mekanism/textures/block/bin/creative_side.png
  kubejs/assets/mekanism/textures/block/bin/creative_side_on.png
  kubejs/assets/mekanism/textures/block/bin/creative_top.png
  kubejs/assets/mekanism/textures/block/bin/creative_top_on.png
  kubejs/assets/mekanism/textures/block/bin/elite_front.png
  kubejs/assets/mekanism/textures/block/bin/elite_front_on.png
  kubejs/assets/mekanism/textures/block/bin/elite_side.png
  kubejs/assets/mekanism/textures/block/bin/elite_side_on.png
  kubejs/assets/mekanism/textures/block/bin/elite_top.png
  kubejs/assets/mekanism/textures/block/bin/elite_top_on.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_front.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_front_on.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_side.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_side_on.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_top.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_top_on.png
Labels: Maintenance

#1513 Add IE Creosote as valid fuel for PNC
  config/aquaculture-common-1.toml.bak
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/fuels.js
Labels: Enhancement

#1516 Corrected purple/blue pickerelweed outputs
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
Labels: Enhancement

#1521 remove duplicate ore and dust smelting recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/blasting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smelting.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Enhancement

#1539 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.3.md
  remove-client-configs.ps1
Labels: Maintenance

#1544 Add Astral Starmetal to Forge tags for smelting
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Script

#1551 Allows uraninite to be crafted from blocks and closes #1546
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Bug

#1555 Fixes Farmer's Delights Knives smelting into Iron and Gold Nuggets.
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/blasting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smelting.js
Labels: Bug

#1557 Add Building Gadgets Patterns for Compact Crafting
  building_gadgets_patterns/compact_crafting/README.txt
  building_gadgets_patterns/compact_crafting/giant.txt
  building_gadgets_patterns/compact_crafting/large.txt
  building_gadgets_patterns/compact_crafting/maximum.txt
  building_gadgets_patterns/compact_crafting/normal.txt
  building_gadgets_patterns/compact_crafting/projectors_max.txt
  building_gadgets_patterns/compact_crafting/small.txt
  building_gadgets_patterns/compact_crafting/tiny.txt
Labels: Enhancement

#1567 Tweaked the output of bonemeal mortar recipe to make it worth something
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_dyes.js
Labels: Enhancement

#1575 Added convenient recipes for drawers using every wood type
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Enhancement

#1591 Fixed drawer recipes
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Maintenance

#1583 Aquaculture integration
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/farmersdelight/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/aquaculture/driftwood_logs.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/cooked_fishes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushroom_colonies.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/raw_fishes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/knives.js
  kubejs/server_scripts/enigmatica/kubejs/constants/disabled_items.js
Labels: Enhancement

#1605 fixed drawers again
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Maintenance

#1608 Quartz Chunks from Laser Drill
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
Labels: Development

#1609 Re-add missing Chunk to Ore Shapeless Recipes
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Development

#1556 repurposed structures preset, with some structure changes
  config/terraforged/biome_weights.conf
  config/terraforged/presets/Enigmatica.json
  config/towers_of_the_wild-common.toml
Labels: Development

#1621 Add Supplementaries Flax to Market
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/supplementaries_seeds.json
Labels: Development

#1641 Added Torch Recipe for Stick + Standing Fire
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Enhancement

#1660 IE and PNC Gun Damage Boosts (and IE Excavator speed boost)
  config/pneumaticcraft-common.toml
  defaultconfigs/immersiveengineering-server.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/blueprint.js
Labels: Enhancement

#1670 IE Loot Updates
  kubejs/data/enigmatica/loot_tables/chests/quest_immersive_engineering_loot_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_immersive_engineering_loot_rare.json
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
Labels: Enhancement, Quest

#1665 Mekanism Power Pass
  config/Mekanism/general.toml
  config/Mekanism/generators.toml
Labels: Development

#1673 Create Integrated Dynamics Loot Chest
  kubejs/data/enigmatica/loot_tables/chests/quest_integrated_dynamics_loot_rare.json
Labels: Development

#1674 added driftwood washing recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
Labels: Enhancement

#1676 Limit Powah Upgrade Recipes to Only prior tiers
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/constants/powah.js
Labels: Development

#1659 Update squeezer.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/squeezer.js
Labels: Development

#1679 Tag updates
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/create/fan_heaters.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/create/fan_transparent.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/farmersdelight/heat_sources.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/farmersdelight/tray_heat_sources.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/minecraft/campfires.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/minecraft/fire.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/create/upright_on_belt.js
  kubejs/server_scripts/enigmatica/kubejs/constants/fish.js
  kubejs/server_scripts/enigmatica/kubejs/constants/heat_sources.js
Labels: Enhancement

#1688 Add extra hot and cold blocks to PNC and Powah
  config/powah/general_common.toml
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/betterendforge/ancient_emerald_ice.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/betterendforge/dense_emerald_ice.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/betterendforge/emerald_ice.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/byg/boric_campfire.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/byg/cryptic_campfire.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/byg/cryptic_magma.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/byg/magmatic_stone.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/create/blaze_burner_fading.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/create/blaze_burner_kindled.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/create/blaze_burner_seething.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/create/blaze_burner_smouldering.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/decorative_blocks/brazier.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/decorative_blocks/soul_brazier.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/emendatusenigmatica/uranium.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/minecraft/soul_campfire.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/occultism/spirit_fire.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/powah/blazing_crystal_block.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/powah/uraninite.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/quark/magma_bricks.json
  kubejs/data/pneumaticcraft/pneumaticcraft/block_heat_properties/valhelsia_structures/brazier.json
Labels: Development

#1730 Add Recipes for Artifact Level Infinity Tools
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/nucleosynthesizing.js
Labels: Enhancement

#1727 Reverse-stonecutting
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/stonecutter.js
Labels: Enhancement

#1733 Added create cobblestones smelting recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smelting.js
Labels: Enhancement

#1739 Infinity tools update
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/nucleosynthesizing.js
Labels: Development

#1750 Update Insolator and Cloche to reduce rare drops like poison potatoes
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_growables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
Labels: Development

#1760 Issue Templates and Image Compression
  .github/ISSUE_TEMPLATE/bug-report.md
  kubejs/assets/curios/textures/item/empty_goggles_slot.png
  kubejs/assets/kubejs/textures/item/quintuple_alfsteel_ingot.png
Labels: Maintenance

#1762 Last minute changes and changelog
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.4.md
  github-changelog-generator.bat
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_growables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  minecraftinstance.json
Labels: Maintenance

#1765 Really remove Powah's starter blocks
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/constants/powah.js
Labels: Maintenance

#1768 Add byg stones to the stonecutter tweaks
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/stonecutter.js
Labels: Enhancement

#1782 0.4.5
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/jei/recipe-category-sort-order.ini
  config/naturesaura-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_fluid_to_xp.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_stoneworks.js
  kubejs/server_scripts/enigmatica/kubejs/constants/disabled_items.js
  kubejs/server_scripts/enigmatica/kubejs/constants/powah.js
  minecraftinstance.json
Labels: Maintenance

#1783 0.4.5 part 2 ^^'
  config/serverconfigupdater-common.toml
  minecraftinstance.json
  settings.ps1
Labels: Maintenance

#1784 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.5.md
Labels: Maintenance

#1787 Lots of beeutiful changes
  .gitignore
  config/resourcefulbees/bees/Aluminum.json
  config/resourcefulbees/bees/Blaze.json
  config/resourcefulbees/bees/Boobee.json
  config/resourcefulbees/bees/Brass.json
  config/resourcefulbees/bees/Bronze.json
  config/resourcefulbees/bees/Clay.json
  config/resourcefulbees/bees/Coal.json
  config/resourcefulbees/bees/Constantan.json
  config/resourcefulbees/bees/Copper.json
  config/resourcefulbees/bees/Creeper.json
  config/resourcefulbees/bees/Diamond.json
  config/resourcefulbees/bees/Electrum.json
  config/resourcefulbees/bees/Emerald.json
  config/resourcefulbees/bees/Ender.json
  config/resourcefulbees/bees/Enderium.json
  config/resourcefulbees/bees/Ghast.json
  config/resourcefulbees/bees/Glowstone.json
  config/resourcefulbees/bees/Gold.json
  config/resourcefulbees/bees/Gravel.json
  config/resourcefulbees/bees/Icy.json
  config/resourcefulbees/bees/Invar.json
  config/resourcefulbees/bees/Iron.json
  config/resourcefulbees/bees/Lapis.json
  config/resourcefulbees/bees/Lead.json
  config/resourcefulbees/bees/Lumium.json
  config/resourcefulbees/bees/Netherite.json
  config/resourcefulbees/bees/Nickel.json
  config/resourcefulbees/bees/Obsidian.json
  config/resourcefulbees/bees/Osmium.json
  config/resourcefulbees/bees/Pigman.json
  config/resourcefulbees/bees/Redstone.json
  config/resourcefulbees/bees/Sand.json
  config/resourcefulbees/bees/Signalum.json
  config/resourcefulbees/bees/Silver.json
  config/resourcefulbees/bees/Skeleton.json
  config/resourcefulbees/bees/Slimy.json
  config/resourcefulbees/bees/Steel.json
  config/resourcefulbees/bees/Tin.json
  config/resourcefulbees/bees/Uranium.json
  config/resourcefulbees/bees/Water.json
  config/resourcefulbees/bees/Wither.json
  config/resourcefulbees/bees/Zinc.json
  config/resourcefulbees/bees/Zombie.json
  config/resourcefulbees/bees/nether_quartz.json
Labels: Development

#1802 Fix Apiary Recipies
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Bug

#1811 Pedestals Quests
  config/ftbquests/quests/chapters/pedestals.snbt
  kubejs/data/enigmatica/loot_tables/chests/quest_pedestals_loot_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_pedestals_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/chests/quest_pedestals_loot_rare.json
Labels: Enhancement

#1812 Merge Bee changes into Develop
  .gitignore
  config/ftbquests/quests/chapters/pedestals.snbt
  config/resourcefulbees/bees/Aluminum.json
  config/resourcefulbees/bees/Blaze.json
  config/resourcefulbees/bees/Boobee.json
  config/resourcefulbees/bees/Brass.json
  config/resourcefulbees/bees/Bronze.json
  config/resourcefulbees/bees/Clay.json
  config/resourcefulbees/bees/Coal.json
  config/resourcefulbees/bees/Constantan.json
  config/resourcefulbees/bees/Copper.json
  config/resourcefulbees/bees/Creeper.json
  config/resourcefulbees/bees/Diamond.json
  config/resourcefulbees/bees/Electrum.json
  config/resourcefulbees/bees/Emerald.json
  config/resourcefulbees/bees/Ender.json
  config/resourcefulbees/bees/Enderium.json
  config/resourcefulbees/bees/Ghast.json
  config/resourcefulbees/bees/Glowstone.json
  config/resourcefulbees/bees/Gold.json
  config/resourcefulbees/bees/Gravel.json
  config/resourcefulbees/bees/Icy.json
  config/resourcefulbees/bees/Invar.json
  config/resourcefulbees/bees/Iron.json
  config/resourcefulbees/bees/Lapis.json
  config/resourcefulbees/bees/Lead.json
  config/resourcefulbees/bees/Lumium.json
  config/resourcefulbees/bees/Netherite.json
  config/resourcefulbees/bees/Nickel.json
  config/resourcefulbees/bees/Obsidian.json
  config/resourcefulbees/bees/Osmium.json
  config/resourcefulbees/bees/Pigman.json
  config/resourcefulbees/bees/Redstone.json
  config/resourcefulbees/bees/Sand.json
  config/resourcefulbees/bees/Signalum.json
  config/resourcefulbees/bees/Silver.json
  config/resourcefulbees/bees/Skeleton.json
  config/resourcefulbees/bees/Slimy.json
  config/resourcefulbees/bees/Steel.json
  config/resourcefulbees/bees/Tin.json
  config/resourcefulbees/bees/Uranium.json
  config/resourcefulbees/bees/Water.json
  config/resourcefulbees/bees/Wither.json
  config/resourcefulbees/bees/Zinc.json
  config/resourcefulbees/bees/Zombie.json
  config/resourcefulbees/bees/nether_quartz.json
Labels: Maintenance

#1823 0.4.7 + Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.7.md
  minecraftinstance.json
  settings.ps1
Labels: Maintenance

#1835 Restore Pedestal's cobble and stoneworks
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_stoneworks.js
Labels: Maintenance

#1836 Fix beam stonecutting recipes
  kubejs/server_scripts/enigmatica/kubejs/constants/beams.js
Labels: Bug

#1845 PVJ, Farmers Delight, and BYG Integration Update
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushroom_caps.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushroom_stems.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushrooms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/minecraft/leaves.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
Labels: Maintenance

#1841 Split up Masonry wall/slab stonecutting recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/stonecutter.js
Labels: Enhancement

#1849 Move material substitution tags into it's own script and refactor
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/dusts.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/gears.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ingots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/material_substitutes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/nuggets.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
Labels: Development

#1860 Merge Master into Develop to get a PR on-dev
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/curios/goggles.js
Labels: Maintenance

#1868 Buff IF Fluid Laser BM Life Essence Recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_fluid.js
Labels: Enhancement

#1880 Fix RS tooltips
  kubejs/client_scripts/item_modifiers/tooltips.js
Labels: Maintenance
