Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-01, with the labels that each got.

#713 Astral Sorcery Loot Tables
  kubejs/data/enigmatica/loot_tables/chests/quest_astral_sorcery_loot_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_astral_sorcery_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/chests/quest_astral_sorcery_loot_rare.json
Labels: Enhancement

#719 Add custom values to names.cfg
  config/apotheosis/names.cfg
Labels: Enhancement

#736 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.3.txt
Labels: Maintenance

#741 Uranium was improperly tagged as a Nether Only ore in the laser drill
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
Labels: Bug

#742 Update 0.3.4 Hotfix
  config/ars_nouveau-common.toml
  config/jaopca/materials/arcane_gold.toml
  config/jaopca/materials/pewter.toml
  config/jei/ingredient-list-mod-sort-order.ini
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
  minecraftinstance.json
Labels: Maintenance

#743 changelogs, modpack version bump, modlist update
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.4.txt
  settings.ps1
Labels: Maintenance

#744 Disabled Certus Quartz from Spawning
  .github/README.md
  config/emendatusenigmatica-common.toml
Labels: Bug

#748 Fix for Create Processing
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/create/crushed_ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/additions.js
  kubejs/server_scripts/enigmatica/kubejs/global_constants.js
Labels: Enhancement

#745 IE and TS Ore Updates (add missing secondaries)
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crusher.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
Labels: Enhancement

#760 disabled quark bone to bonemeal smelt recipe
  config/quark-common.toml
Labels: Bug

#777 RFtools Loot
  kubejs/data/enigmatica/loot_tables/chests/quest_rftools_loot_rare.json
Labels: Bug

#780 Update Wood List
  kubejs/server_scripts/enigmatica/kubejs/constants.js
Labels: Enhancement

#778 Implementation of Supplementaries
  config/supplementaries-common.toml
  config/supplementaries-registry.toml
  kubejs/client_scripts/item_modifiers/constants.js
Labels: Enhancement

#836 Change Cobbleworks so it doens't interfere with basic cobble generators.
  config/cobblegenrandomizer-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_cobblegen.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
Labels: Enhancement

#839 Valid Apiary Block updates
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/resourcefulbees/valid_apiary.js
Labels: Enhancement

#835 Occultism progression fixes
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/occultism_saplings.json
  kubejs/data/occultism/recipes/spirit_trade/4x_stone_to_otherstone.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/spirit_fire.js
Labels: Enhancement

#870 IE Storage Crate Update
  kubejs/data/immersiveengineering/loot_tables/chests/engineers_house.json
Labels: Enhancement

#891 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.6.txt
Labels: Maintenance

#937 Fix for missing Create Gearshift recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Bug

#940 Tag Maintenance
  kubejs/client_scripts/item_modifiers/jei_hide.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/boots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/chests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/helms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/legs.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bags.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bulk.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/energy.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/liquids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/axes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/hoes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/pickaxes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/shovels.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/melee.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/ranged.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/swords.js
Labels: Maintenance

#967 Ars Nouveau Tweaks
  kubejs/data/ars_nouveau/recipes/amulet_of_mana_boost.json
  kubejs/data/ars_nouveau/recipes/amulet_of_mana_regen.json
  kubejs/data/ars_nouveau/recipes/arcane_relay.json
  kubejs/data/ars_nouveau/recipes/arcane_relay_splitter.json
  kubejs/data/ars_nouveau/recipes/belt_of_levitation.json
  kubejs/data/ars_nouveau/recipes/carbuncle_charm.json
  kubejs/data/ars_nouveau/recipes/dominion_wand.json
  kubejs/data/ars_nouveau/recipes/mana_bloom_crop.json
  kubejs/data/ars_nouveau/recipes/ring_of_greater_discount.json
  kubejs/data/ars_nouveau/recipes/ring_of_lesser_discount.json
  kubejs/data/ars_nouveau/recipes/spell_bow.json
  kubejs/data/ars_nouveau/recipes/spell_turret.json
  kubejs/data/ars_nouveau/recipes/summoning_crystal.json
  kubejs/data/ars_nouveau/recipes/sylph_charm.json
  kubejs/data/ars_nouveau/recipes/wand.json
  kubejs/data/ars_nouveau/recipes/whelp_charm.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ingots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/nuggets.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
Labels: Bug, Enhancement

#969 Steel Processing
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Enhancement

#975 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.7.txt
Labels: Maintenance

#981 Move removals out of induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Maintenance

#999 Creosote Unification
  kubejs/data/thermal/recipes/machine/pyrolyzer/pyrolyzer_coal.json
  kubejs/data/thermal/recipes/machine/pyrolyzer/pyrolyzer_logs.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/interactio/item_fluid_transform.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/compression.js
Labels: Enhancement

#1002 BM Compatibility Review
  kubejs/client_scripts/item_modifiers/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_output.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/additions.js
Labels: Maintenance

#1007 Honey Unification
  kubejs/client_scripts/item_modifiers/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide.js
  kubejs/data/create/recipes/emptying/honey_bottle.json
  kubejs/data/create/recipes/filling/honey_bottle.json
  kubejs/data/thermal/recipes/machine/bottler/bottler_honey_bottle.json
  kubejs/data/thermal/recipes/machine/chiller/chiller_honey_to_honey_block.json
  kubejs/data/thermal/recipes/machine/crucible/crucible_honey_block_to_honey.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/emptying.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/filling.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/heat_frame_cooling.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/chiller.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/crucible.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/minecraft/fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/minecraft/fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/resourcefulbees/honey.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
Labels: Enhancement

#1024 Changelog
  changelogs/CHANGELOG.md
Labels: Maintenance

#1039 0.3.9
  .github/ISSUE_TEMPLATE/suggestion.md
  config/Mekanism/general.toml
  config/akashictome-common.toml
  config/cobblegenrandomizer-common.toml
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/tools.snbt
  config/ftbquests/quests/data.snbt
  config/occultism-common.toml
  kubejs/client_scripts/global_constants.js
  kubejs/client_scripts/item_modifiers/constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/jei_hide.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/infuser.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching_byg_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/blasting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/campfire_cooking.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smelting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smoking.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_cobblegen.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/stones.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/resourcefulbees/valid_apiary.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/dusts.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/stones.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/resourcefulbees/valid_apiary.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/additions.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
  kubejs/server_scripts/enigmatica/kubejs/global_constants.js
  minecraftinstance.json
  settings.ps1
Labels: Maintenance

#1040 Changelog (mostly)
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.9.txt
  config/supplementaries-common.toml
Labels: Maintenance

#1055 Create Empty Placeholders for Removed Scripts
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching_byg_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge_flowers.js
Labels: Maintenance

#1061 0.3.10
  config/akashictome-common.toml
  config/immersiveengineering-common.toml
  config/jei/recipe-category-sort-order.ini
  config/occultism-common.toml
  config/quark-common.toml
  config/resourcefulbees/bees/Ghast.json
  config/resourcefulbees/bees/Wither.json
  config/serverconfigupdater-common.toml
  defaultconfigs/occultism-server.toml
  development/include-in-server-files/settings.cfg
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/global_constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/jei_hide.js
  kubejs/client_scripts/item_modifiers/jei_hide_fluids.js
  kubejs/client_scripts/item_modifiers/jei_hide_items.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching_byg_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge_flowers.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/minecraft/fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/dustrialdecor/dustrialdecor.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
  minecraftinstance.json
  settings.ps1
Labels: Maintenance

#1062 Update settings.cfg
  development/include-in-server-files/settings.cfg
Labels: Maintenance

#1085 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.10.txt
  minecraftinstance.json
Labels: Maintenance

#1096 Fixed RS Grids not showing up in JEI and allow for any colored crafter to be used in recipes
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide_items.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
Labels: Bug

#1109 Blacklist Mimicubes from spawners
  config/apotheosis/spawner.cfg
  config/pneumaticcraft-common.toml
Labels: Bug

#1108 Add Glitterkelp to Insolator and Botany Pots
  kubejs/data/botanypots/recipes/crops/glitterkelp.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/insolator.js
Labels: Enhancement

#1135 Unify candles under forge:candles tag
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/candles.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/candles.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
Labels: Enhancement

#1137 0.3.11
  .github/README.md
  .gitignore
  RemoveClientConfigs.bat
  RemoveClientConfigs.bat.ps1
  building_gadgets_patterns/mekanism/basic_thermo_electric_boiler.txt
  config/apotheosis/spawner.cfg
  config/cobblegenrandomizer-common.toml
  config/ftbquests/quests/chapters/challenges.snbt
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_3_wip.snbt
  config/ftbquests/quests/chapters/gates_wip.snbt
  config/ftbquests/quests/chapters/mekanism.snbt
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/storage.snbt
  config/ftbquests/quests/chapters/tools.snbt
  config/ftbquests/quests/data.snbt
  config/industrialforegoing/machine-misc.toml
  config/industrialforegoing/modules.toml
  config/jei/recipe-category-sort-order.ini
  config/pneumaticcraft-common.toml
  config/quark-common.toml
  config/serverconfigupdater-common.toml
  config/supplementaries-common.toml
  config/supplementaries-registry.toml
  config/toolstats-client.toml
  defaultconfigs/rftoolsbase-server.toml
  development/include-in-server-files/server-guide.txt
  development/include-in-server-files/settings.cfg
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/jei_hide_items.js
  kubejs/data/botanypots/recipes/crops/glitterkelp.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crusher.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/injecting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smithing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/bottler.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/bottler_experience.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/insolator.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/candles.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/quests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/candles.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/additions.js
  kubejs/server_scripts/enigmatica/kubejs/constants.js
  kubejs/server_scripts/enigmatica/kubejs/functions.js
  minecraftinstance.json
  settings.ps1
Labels: Maintenance

#1138 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.11.txt
  minecraftinstance.json
Labels: Maintenance

#1154 0.3.12
  config/alexsmobs-biomes.toml
  config/alexsmobs.toml
  config/apotheosis/deadly.cfg
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/powah.snbt
  config/ftbquests/quests/chapters/rftools_wip.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/ftbquests/quests/data.snbt
  config/invtweaks-client.toml
  config/jei/ingredient-list-mod-sort-order.ini
  config/quark-common.toml
  minecraftinstance.json
  settings.ps1
Labels: Maintenance

#1157 0.3.12 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.3.12.txt
Labels: Maintenance
