Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-06, with the labels that each got.

#2325 Disable Environmental Pies
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/fruits.js
Labels: Development

#2327 update pies to use fruit tags instead
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Development

#2322 Astral Sorcery - Rock Crystal Ore retexture
  kubejs/assets/astralsorcery/models/block/multilayer/rock_crystal_ore.json
  kubejs/assets/astralsorcery/textures/block/ore_rockcrystal.png
Labels: Enhancement

#2324 Atum Integration pass #1
  kubejs/assets/enigmatica/lang/en_us.json
  kubejs/assets/immersiveengineering/lang/en_us.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/atum_saplings.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/atum_seeds.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/environmental_saplings.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/environmental_seeds.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/minerals.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/rftoolsutility/spawner.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/boots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/chests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/helms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/legs.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/eggs.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/basic.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/axes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/hoes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/pickaxes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/shovels.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/melee.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/ranged.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/swords.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_dyes.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_growables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: Development

#2337 Pretty Fluid Pipes Recipe Thermalization
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Enhancement

#2338 Create Alchemy Table recipe for Cured Rubber
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Enhancement

#2339 Adventure Quests Updates
  config/ftbquests/quests/chapters/adventure.snbt
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/ftbquests/quests/chapters/tools.snbt
Labels: Enhancement, Quest

#2340 minor text quest formatting
  config/ftbquests/quests/chapters/adventure.snbt
Labels: Development

#2342 Add Hive UpgradeRecipes
  kubejs/client_scripts/normal/item modifiers/jei_descriptions.js
  kubejs/client_scripts/normal/item modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/hive_upgrade_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/resourcefulbees/hive_upgrade_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/resourcefulbees/hive_upgrade_recipe.js
Labels: Bug

#2343 BetterEnd stones added to stonecutter
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/atum/atum.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#2344 Mob Duplication Blacklists
  config/pneumaticcraft-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/mob_imprisonment_tool_blacklist.js
Labels: Enhancement

#2349 Fixes Conflicting Glass Smelting from BYG
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#2353 Add Slime block tags for realzies
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/slime_block.js
Labels: Development

#2355 Akashic Tome update
  config/akashictome-common.toml
  config/ftbquests/quests/chapters/getting_started.snbt
  kubejs/client_scripts/item_modifiers/jei_add_items.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#2356 Paper rebalance
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/shapeless_fluid.js
Labels: Enhancement

#2357 Buff Create Paper recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/compacting.js
Labels: Enhancement

#2360 Hide Tinker workstations and anvils
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_add_items.js
Labels: Development

#2366 Separate Prismarine and Prismarine Bricks in Stonecutter
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#2367 Re-enable/fix Compact Machine quests. Add quest to point to Occultism Storage.
  config/ftbquests/quests/chapters/storage.snbt
Labels: Enhancement

#2370 Botania utility[Expert] Redstring and Corporea rework
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/candle_materials.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/farmersdelight/cooking_pot.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/replace_input.js
Labels: Development

#2369 [Expert] Switch to Quark as base candle
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/candle_materials.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/farmersdelight/cooking_pot.js
Labels: Development

#2372 Make Nebu nuggets craftable from ingots
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Development

#2377 Implement Hide Recipe from JEI list
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide_recipes.js
Labels: Development

#2382 Create Windmill Quest - clarify the difference between glue and slime
  config/ftbquests/quests/chapters/create.snbt
Labels: Enhancement

#2396 EE 1.2.5 Texture Unification
  kubejs/assets/bloodmagic/textures/item/fragment_netherite_scrap.png
  kubejs/assets/bloodmagic/textures/item/goldfragment.png
  kubejs/assets/bloodmagic/textures/item/goldgravel.png
  kubejs/assets/bloodmagic/textures/item/gravel_netherite_scrap.png
  kubejs/assets/bloodmagic/textures/item/ironfragment.png
  kubejs/assets/bloodmagic/textures/item/irongravel.png
  kubejs/assets/create/textures/block/palettes/gabbro/plain.png
  kubejs/assets/create/textures/block/palettes/limestone/plain.png
  kubejs/assets/create/textures/block/palettes/natural_scoria.png
  kubejs/assets/create/textures/block/palettes/scoria/plain.png
  kubejs/assets/create/textures/block/palettes/weathered_limestone/plain.png
  kubejs/assets/create/textures/item/crushed_aluminum_ore.png
  kubejs/assets/create/textures/item/crushed_brass.png
  kubejs/assets/create/textures/item/crushed_copper_ore.png
  kubejs/assets/create/textures/item/crushed_gold_ore.png
  kubejs/assets/create/textures/item/crushed_iron_ore.png
  kubejs/assets/create/textures/item/crushed_lead_ore.png
  kubejs/assets/create/textures/item/crushed_nickel_ore.png
  kubejs/assets/create/textures/item/crushed_osmium_ore.png
  kubejs/assets/create/textures/item/crushed_silver_ore.png
  kubejs/assets/create/textures/item/crushed_tin_ore.png
  kubejs/assets/create/textures/item/crushed_uranium_ore.png
  kubejs/assets/create/textures/item/crushed_zinc_ore.png
  kubejs/assets/mekanism/textures/item/clump_copper.png
  kubejs/assets/mekanism/textures/item/clump_gold.png
  kubejs/assets/mekanism/textures/item/clump_iron.png
  kubejs/assets/mekanism/textures/item/clump_lead.png
  kubejs/assets/mekanism/textures/item/clump_osmium.png
  kubejs/assets/mekanism/textures/item/clump_tin.png
  kubejs/assets/mekanism/textures/item/clump_uranium.png
  kubejs/assets/mekanism/textures/item/crystal_copper.png
  kubejs/assets/mekanism/textures/item/crystal_gold.png
  kubejs/assets/mekanism/textures/item/crystal_iron.png
  kubejs/assets/mekanism/textures/item/crystal_lead.png
  kubejs/assets/mekanism/textures/item/crystal_osmium.png
  kubejs/assets/mekanism/textures/item/crystal_tin.png
  kubejs/assets/mekanism/textures/item/crystal_uranium.png
  kubejs/assets/mekanism/textures/item/dirty_dust_copper.png
  kubejs/assets/mekanism/textures/item/dirty_dust_gold.png
  kubejs/assets/mekanism/textures/item/dirty_dust_iron.png
  kubejs/assets/mekanism/textures/item/dirty_dust_lead.png
  kubejs/assets/mekanism/textures/item/dirty_dust_osmium.png
  kubejs/assets/mekanism/textures/item/dirty_dust_tin.png
  kubejs/assets/mekanism/textures/item/dirty_dust_uranium.png
  kubejs/assets/mekanism/textures/item/shard_copper.png
  kubejs/assets/mekanism/textures/item/shard_gold.png
  kubejs/assets/mekanism/textures/item/shard_iron.png
  kubejs/assets/mekanism/textures/item/shard_lead.png
  kubejs/assets/mekanism/textures/item/shard_osmium.png
  kubejs/assets/mekanism/textures/item/shard_tin.png
  kubejs/assets/mekanism/textures/item/shard_uranium.png
Labels: Enhancement

#2400 Refactoring unify_materials
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
Labels: Development

#2406 Unify Materials update
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
Labels: Development

#2407 More Bee Updates
  config/ftbquests/quests/chapters/resourceful_bees.snbt
  config/resourcefulbees/bees/metal/Cobalt.json
  config/resourcefulbees/bees/natural/Ender.json
  config/resourcefulbees/bees/natural/Glowstone.json
  config/resourcefulbees/bees/natural/Obsidian.json
  config/resourcefulbees/bees/natural/Pigman.json
  config/resourcefulbees/bees/nether/Blaze.json
  config/resourcefulbees/bees/nether/Ghast.json
  config/resourcefulbees/bees/nether/nether_quartz.json
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
Labels: Enhancement

#2411 Clean up tinker's bronze, remove deprecated pedestals items, revert TNT crushing for expert.
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_explode.js
Labels: Development

#2413 more TC alloy compat
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Development

#2421 EE Recipes for new materials
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide_fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Development

#2422 Update constants.js
  kubejs/client_scripts/constants.js
Labels: Development

#2425 Adds casting recipes for EE fluids not represented by Tinkers
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Development

#2426 0.5.0 take 2/?
  MODLIST.md
  automation/.build.json
  automation/start-automated-server.bat
  automation/update-server.ps1
  changelogs/CHANGELOG.md
  config/emendatusenigmatica-common.toml
  config/quark-common.toml
  config/tconstruct-common.toml
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide_fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  minecraftinstance.json
  server_files/server-setup-config.yaml
Labels: Maintenance

#2427 add cobalt to laser drill
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
Labels: Development

#2434 Replace obsolete hammer reward with a potion
  config/ftbquests/quests/chapters/tetra.snbt
Labels: Maintenance

#2443 EE Melting Recipes
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
Labels: Development

#2450 Add compat for ore melting to TiC
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Development

#2448 Journeymap Bees 2.0
  kubejs/assets/resourcefulbees/textures/entity_icon/custom/bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/kitten/bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/ores/coal/coal_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/boobee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/ender.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/ghast.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/glowstone.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/icy.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/obsidian.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/sand.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/water.png
  kubejs/assets/resourcefulbees/textures/entity_icon/slime/slime_bee.png
Labels: Enhancement

#2457 Re-add Ingot/Gem to Dust recipe unification
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Maintenance

#2465 Update Thermal Loot Table
  kubejs/data/enigmatica/loot_tables/chests/quest_thermal_series_loot_rare.json
Labels: Development

#2479 More refactoring of unify_materials
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/shaped.js
Labels: Development

#2480 Normalize output quantities for crafting drawers
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Enhancement

#2473 [Expert] Begin Introducing Atum items into Magic Mods
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#2466 [Expert] Rebalance Cutting Fluid crafting
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/cutting_essence.png
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#2493 Add ways to obtain various BYG nether items such as mushrooms
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/architects_palette/warping.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/corals.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushrooms.js
Labels: Maintenance

#2495 [Expert] Low End Equipment Pass
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/betterend/anvil_smithing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/minecraft/smithing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Development

#2505 Clarify quest text from Shift+Click to Sneak+Click
  config/ftbquests/quests/chapters/pedestals.snbt
  config/ftbquests/quests/chapters/powah.snbt
Labels: Enhancement

#2506 Clarify quest text from Shift+Click to Sneak+Click
  config/ftbquests/quests/chapters/refined_storage.snbt
  config/ftbquests/quests/chapters/rftools_wip.snbt
Labels: Enhancement

#2509 [Expert] Alternate recipes for Eidolon ingredients to facilitate automation
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
Labels: Development

#2514 Wither Bone Unification
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/architects_palette/withered_bones.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/bones.js
Labels: Enhancement

#2518 [Expert] Outlining progression via temp(ish) quests and more changes to progression
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/array.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/petal_apothecary.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/animal_spawner.js
Labels: Development

#2529 Mekanism Fusion Fuel Production Buff
  config/Mekanism/general.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/chemical_infusing.js
Labels: Enhancement

#2531 [Worldgen] Bigger Beaches
  config/terraforged/presets/Enigmatica.json
Labels: Enhancement

#2534 [Expert] Magic Progression Mapping and Fixes
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/arc.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/mana_infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/mythicbotany_infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/botania/terra_plate.js
Labels: Development

#2542 Changelogs
  changelogs/CHANGELOG.md
  changelogs/changelog_mods_0.5.1.md
  changelogs/modlist_0.5.1.md
  minecraftinstance.json
  server_files/server-setup-config.yaml
Labels: Development

#2544 Set up tags for Occultism Books to allow automation via RS
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/occultism/book_of_binding.js
Labels: Enhancement

#2552 Adds various new rituals to occultism quest line.
  config/ftbquests/quests/chapters/occultism.snbt
Labels: Enhancement

#2555 DungeonCrawl - Create DeadSea and Ocean themes
  kubejs/data/dungeoncrawl/theming/mappings/sub_theme_mapping.json
  kubejs/data/dungeoncrawl/theming/mappings/theme_mapping.json
  kubejs/data/dungeoncrawl/theming/sub_themes/deadsea.json
  kubejs/data/dungeoncrawl/theming/sub_themes/ocean.json
  kubejs/data/dungeoncrawl/theming/themes/deadsea.json
  kubejs/data/dungeoncrawl/theming/themes/ocean.json
Labels: Enhancement

#2560 DungeonCrawl - Create Bastion Theme
  kubejs/data/dungeoncrawl/theming/sub_themes/bastion_2.json
  kubejs/data/dungeoncrawl/theming/themes/bastion_2.json
Labels: Enhancement

#2562 DungeonCrawl - Create Clockwork Theme
  kubejs/data/dungeoncrawl/theming/sub_themes/nether.json
  kubejs/data/dungeoncrawl/theming/themes/clockwork.json
Labels: Enhancement

#2558 Removed Quark buttons from crafting station's GUI
  config/quark-common.toml
Labels: Bug

#2565 fix to ID for ocean sub theme
  kubejs/data/dungeoncrawl/theming/sub_themes/ocean.json
Labels: Development

#2569 Actually enable the new Dungeon Crawl themes
  kubejs/data/dungeoncrawl/theming/randomizers/default.json
Labels: Development

#2577 [Expert] Tiered Apiary Recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
Labels: Development

#2580 Change BooBee "Flower"
  config/resourcefulbees/bees/special/Boobee.json
Labels: Maintenance

#2583 Tooltip explaining how to obtain Ham from Farmer's Delight
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
Labels: Enhancement

#2590 Increase shapeless crafting yield of Pewter to 2 for 2 dusts input.
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#2591 Add Cobalt to Orechid and Dimensional Mineshaft
  kubejs/data/botania/orechid_ore_weights/orechid_ignem.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_basic_resources.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_ores.js
Labels: Enhancement
