Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-08, with the labels that each got.

#2869 Fix Occultism Stone to Otherstone trade
  kubejs/data/occultism/recipes/spirit_trade/4x_stone_to_otherstone.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/spirit_trade.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/spirit_trade.js
Labels: Enhancement

#2872 Create Tag script for adding blocks to the Sylph pool
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/ars_nouveau/sylph_liked.js
Labels: Development

#2875 Fix Immersive Petroleum asphalt recipes to use tags
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/shaped_fluid.js
Labels: Enhancement

#2878 Blacklist Pharaohs from Apotheosis spawners
  config/apotheosis/spawner.cfg
Labels: Enhancement

#2879 Remove Duplicate Dim Shard processing recipe from Enrichment Chamber
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching.js
Labels: Enhancement

#2877 [Expert] More tweak
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/book_upgrade.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_explode.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/shaped.js
Labels: Development

#2883 [Expert] Enchanting Tweaks
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/jei_hide_recipes.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar.js
Labels: Development

#2891 [Expert] Minor recipe tweaks
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/elven_trade.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
Labels: Development

#2893 Update Yeet script for new KubeJS version
  kubejs/client_scripts/expert/item_modifiers/jei_hide_recipes.js
Labels: Development

#2894 Fix Recipe Yeeting
  kubejs/client_scripts/expert/item_modifiers/jei_hide_recipes.js
Labels: Development

#2896 More Special Bees
  config/resourcefulbees/bee_traits/sedimentary.json
  config/resourcefulbees/bees/gem/Diamond.json
  config/resourcefulbees/bees/gem/Emerald.json
  config/resourcefulbees/bees/gem/Lapis.json
  config/resourcefulbees/bees/gem/Redstone.json
  config/resourcefulbees/bees/metal/Aluminum.json
  config/resourcefulbees/bees/metal/Cobalt.json
  config/resourcefulbees/bees/metal/Copper.json
  config/resourcefulbees/bees/metal/Gold.json
  config/resourcefulbees/bees/metal/Iron.json
  config/resourcefulbees/bees/metal/Lead.json
  config/resourcefulbees/bees/metal/Nickel.json
  config/resourcefulbees/bees/metal/Osmium.json
  config/resourcefulbees/bees/metal/Silver.json
  config/resourcefulbees/bees/metal/Tin.json
  config/resourcefulbees/bees/metal/Uranium.json
  config/resourcefulbees/bees/metal/Zinc.json
  config/resourcefulbees/bees/natural/Coal.json
  config/resourcefulbees/bees/natural/Rocky.json
  config/resourcefulbees/bees/nether/Blaze.json
  config/resourcefulbees/bees/special/Direbee20.json
  config/resourcefulbees/bees/special/GenerikBee.json
  config/resourcefulbees/bees/tech/Basalz.json
  config/resourcefulbees/bees/tech/Blitz.json
  config/resourcefulbees/bees/tech/Blizz.json
  config/resourcefulbees/honey/Rocket.json
  config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/direbee20.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/direbee20_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/generikbee.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/generikbee_angry.png
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/fuels.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/compression.js
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
Labels: Enhancement

#2901 Tinkers' Tool Material Compat
  kubejs/assets/enigmatica/lang/en_us.json
  kubejs/assets/tconstruct/lang/en_us.json
  kubejs/assets/tconstruct/models/tool_materials/aeternium.json
  kubejs/assets/tconstruct/models/tool_materials/alfsteel.json
  kubejs/assets/tconstruct/models/tool_materials/andesite_alloy.json
  kubejs/assets/tconstruct/models/tool_materials/blazing_crystal.json
  kubejs/assets/tconstruct/models/tool_materials/compressed_iron.json
  kubejs/assets/tconstruct/models/tool_materials/elementium.json
  kubejs/assets/tconstruct/models/tool_materials/enderium.json
  kubejs/assets/tconstruct/models/tool_materials/energized_steel.json
  kubejs/assets/tconstruct/models/tool_materials/gaia_spirit.json
  kubejs/assets/tconstruct/models/tool_materials/iesnium.json
  kubejs/assets/tconstruct/models/tool_materials/infused_iron.json
  kubejs/assets/tconstruct/models/tool_materials/livingrock.json
  kubejs/assets/tconstruct/models/tool_materials/livingwood.json
  kubejs/assets/tconstruct/models/tool_materials/lumium.json
  kubejs/assets/tconstruct/models/tool_materials/manasteel.json
  kubejs/assets/tconstruct/models/tool_materials/niotic_crystal.json
  kubejs/assets/tconstruct/models/tool_materials/nitro_crystal.json
  kubejs/assets/tconstruct/models/tool_materials/signalum.json
  kubejs/assets/tconstruct/models/tool_materials/sky.json
  kubejs/assets/tconstruct/models/tool_materials/spirited_crystal.json
  kubejs/assets/tconstruct/models/tool_materials/terminite.json
  kubejs/assets/tconstruct/models/tool_materials/terrasteel.json
  kubejs/assets/tconstruct/models/tool_materials/thallasium.json
  kubejs/assets/tconstruct/models/tool_materials/tin.json
  kubejs/assets/tconstruct/models/tool_materials/treated_wood.json
  kubejs/assets/tconstruct/models/tool_materials/zinc.json
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/materials.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/gems.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
  kubejs/startup_scripts/fluid_registry.js
Labels: Enhancement

#2968 Require 16 stone bricks instead of 8 for nature altar quest
  config/ftbquests/quests/chapters/natures_aura.snbt
Labels: Bug

#2998 Puts the mycelial generator quests in the same order as in JEI
  config/ftbquests/quests/chapters/industrial_foregoing.snbt
Labels: Development

#3012 Bee Crafting - move to Jarred Bees
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/elven_trade.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/mana_infusion.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/casting_table.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mythicbotany/infusion.js
Labels: Enhancement

#3026 Update RBees Quests
  config/ftbquests/quests/chapters/resourceful_bees.snbt
Labels: Maintenance

#3030 0.5.11
  .github/prettifier.yml
  .gitignore
  automation/modpack-uploader.ps1
  automation/settings.ps1
  config/aiimprovements-common.toml
  config/betterburning-common.toml
  config/cobblegenrandomizer-common.toml
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/industrial_foregoing.snbt
  config/ftbquests/quests/chapters/resourceful_bees.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/ftbultimine.json5
  config/pitg-common.toml
  config/repurposed_structures-forge/biome_dimension_allow_disallow_configs.json5
  config/repurposed_structures-forge/strongholds.toml
  config/repurposed_structures-forge/villages.toml
  config/serverconfigupdater-common.toml
  config/terraforged/biome_weights.conf
  defaultconfigs/ftbultimine-server.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/elven_trade.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/mana_infusion.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/casting_basin.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/casting_table.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/compacting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_explode.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mythicbotany/infusion.js
  kubejs/startup_scripts/item_registry.js
  kubejs/startup_scripts/worldgen_add.js
  minecraftinstance.json
Labels: Development

#3042 Bees Update for Bees 0.9.9
  config/resourcefulbees/bees/alloy/Brass.json
  config/resourcefulbees/bees/alloy/Bronze.json
  config/resourcefulbees/bees/alloy/Constantan.json
  config/resourcefulbees/bees/alloy/Electrum.json
  config/resourcefulbees/bees/alloy/Enderium.json
  config/resourcefulbees/bees/alloy/Invar.json
  config/resourcefulbees/bees/alloy/Lumium.json
  config/resourcefulbees/bees/alloy/Signalum.json
  config/resourcefulbees/bees/alloy/Steel.json
  config/resourcefulbees/bees/magic/Bloody.json
  config/resourcefulbees/bees/magic/Elven.json
  config/resourcefulbees/bees/magic/Infused.json
  config/resourcefulbees/bees/magic/Mana.json
  config/resourcefulbees/bees/magic/Sky.json
  config/resourcefulbees/bees/magic/Starry.json
  config/resourcefulbees/bees/magic/Tainted.json
  config/resourcefulbees/bees/magic/Terrestrial.json
  config/resourcefulbees/bees/material/Enderslime.json
  config/resourcefulbees/bees/material/Ichor.json
  config/resourcefulbees/bees/material/Skyslime.json
  config/resourcefulbees/bees/metal/Cobalt.json
  config/resourcefulbees/bees/nether/Blaze.json
  config/resourcefulbees/bees/nether/Ghast.json
  config/resourcefulbees/bees/nether/Netherite.json
  config/resourcefulbees/bees/nether/Wither.json
  config/resourcefulbees/bees/nether/nether_quartz.json
  config/resourcefulbees/bees/special/Boobee.json
  config/resourcefulbees/bees/special/Direbee20.json
  config/resourcefulbees/bees/special/GenerikBee.json
  config/resourcefulbees/bees/special/Wasabee.json
  config/resourcefulbees/bees/tech/Basalz.json
  config/resourcefulbees/bees/tech/Blitz.json
  config/resourcefulbees/bees/tech/Blizz.json
  config/resourcefulbees/bees/tech/Industrious.json
  config/resourcefulbees/bees/tech/PCBee.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/elven_trade.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/mana_infusion.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/casting_table.js
Labels: Enhancement

#3063 Update Ars Nouveau Quests
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Enhancement

#3103 Sourceberry food rework and JEI Descriptions to assist with Dragon Eggs and Fireworks
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#3104 Add Description on leaf pile explaining how to gather them
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
Labels: Enhancement

#3070 [Expert] Proof of Concept - Assembly Table Circuits
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3117 Return of the Custom Apotheosis Bosses
  config/apotheosis/deadly.cfg
  config/apotheosis/names.cfg
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/apotheosis/affix_loot_entries.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/apotheosis/boss_gear.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/apotheosis/bosses.js
Labels: Enhancement

#3118 Convert Expert Occultism Rituals to new datapack format
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#3119 Remove conflicting stone brick smelting recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#3113 I painted (some) bees
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/coal_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/creeper_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/ender_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/icy_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/pigman_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/sand_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/skeleton_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/slimy_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/water_bee.png
  kubejs/assets/ftbchunks/textures/faces/resourcefulbees/zombie_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/creeper/creeper_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/custom/bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/kitten/bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/oreo/oreo_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/ores/coal/coal_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/ender.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/ghast.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/icy.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/sand.png
  kubejs/assets/resourcefulbees/textures/entity_icon/other/water.png
  kubejs/assets/resourcefulbees/textures/entity_icon/pigman/pigman_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/skeleton/skeleton_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/slime/slime_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/slimy/slimy_bee.png
  kubejs/assets/resourcefulbees/textures/entity_icon/zombie/zombie_bee.png
Labels: Enhancement

#3121 Potential fix for Eidolon Lead
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Bug

#3126 Add JEI Description to point people in the right direction for obtaining them
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
Labels: Enhancement

#3129 [Expert] Create crushing and other small changes that probably shoulda been two PRs!
  config/cobblegenrandomizer-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smelting.js
  kubejs/server_scripts/enigmatica/kubejs/constants/cobbleworks.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/minecraft/stonecutter.js
Labels: Development

#3128 [Expert] Extended Initial Compressed Iron Recipe
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_explode.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_fluid_transform.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/press.js
  kubejs/startup_scripts/block_registry.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3139 [Expert] Preliminary restrictions setup
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/hidden_quests.snbt
  config/gamestages/known_stages.json
  kubejs/server_scripts/enigmatica/kubejs/expert/restrictions/restrictions.js
Labels: Development

#3138 [Expert] Armor crafting overhaul
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/boots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/chests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/helms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/legs.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3137 [Expert] Textures for #3128
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  kubejs/assets/kubejs/textures/block/hot_compressed_iron_block.png
  kubejs/assets/kubejs/textures/block/superheated_steel_block.png
  kubejs/assets/kubejs/textures/item/hot_compressed_iron_ingot.png
  kubejs/assets/kubejs/textures/item/superheated_steel_ingot.png
Labels: Development
