Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-02, with the labels that each got.

#1183 update biome_weights.conf
  config/terraforged/biome_weights.conf
Labels: Maintenance

#1184 Refactor Inventory Tilling to fix missing soil to farmland inventory hoeing
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/tool_shapeless.js
Labels: Enhancement

#1186 Add IF Fertilzier, Phyt-Gro, FloralFertilizer, and Red Fertilizer to Immersive Cloche and Thermal Insolator
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/fertilizer.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/insolator_catalyst.js
Labels: Enhancement

#1193 Update Pigman.json
  config/resourcefulbees/bees/Pigman.json
Labels: Bug

#1192 Cleanup Extra Disks from tag additions
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bulk.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/liquids.js
Labels: 0.4.0, Maintenance

#1173 Refactor Scripts to make editing Botany Pots, Cloches, and Insolators easier
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/cloche.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/insolator.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushroom_caps.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_dyes.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_growables.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/general.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: Enhancement

#1195 Fix industrial foregoing sludge refiner cost 1000FE/t
  config/industrialforegoing/machine-resource-production.toml
Labels: Bug

#1203 Script Maintenance and Cleanup
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/sawmill.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/sawmill.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_sawables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/beams.js
  kubejs/server_scripts/enigmatica/kubejs/constants/candles.js
  kubejs/server_scripts/enigmatica/kubejs/constants/cobbleworks.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/general.js
  kubejs/server_scripts/enigmatica/kubejs/constants/materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
  kubejs/server_scripts/enigmatica/kubejs/functions.js
  kubejs/server_scripts/enigmatica/kubejs/unify_outputs.js
Labels: Maintenance

#1204 Update astral_relay BG template
  building_gadgets_patterns/astral_sorcery/astral_relay.txt
Labels: Maintenance

#1210 set defaultWorldType to terraforged
  config/forge-common.toml
  config/terraforged/presets/test 001.json
Labels: Enhancement

#1209 Oil and Bitumen Unification
  kubejs/data/immersivepetroleum/recipes/distillationtower/oilcracking.json
  kubejs/data/immersivepetroleum/recipes/reservoirs/oil.json
  kubejs/data/thermal/recipes/machine/centrifuge/centrifuge_oil_sand.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/forge/fluids.js
Labels: Enhancement

#1125 Mekanism Power Rebalancing - Ethylene is more expensive and slower to make. Fission/Fusion reduced in efficiency
  config/Mekanism/general.toml
  config/Mekanism/generators.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/reaction.js
Labels: 0.4.0, Documentation Required, Enhancement

#1250 Recipe Cleanup and expanding Create's Fan support for more blocks.
  kubejs/client_scripts/item_modifiers/jei_hide_items.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/create/fan_transparent.js
Labels: Maintenance

#1256 Update Umber Hyphae Recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Maintenance

#1248 Powah Rebalance
  config/powah/energy/generators/furnator.toml
  config/powah/energy/generators/magmator.toml
  config/powah/energy/generators/reactor.toml
  config/powah/energy/generators/solar_panel.toml
  config/powah/energy/generators/thermo_gen.toml
  config/powah/general_common.toml
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/powah/powah.js
  kubejs/server_scripts/enigmatica/kubejs/constants/powah.js
Labels: 0.4.0, Enhancement

#1264 Added processing recipes for Limesand to Silicon
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
Labels: Enhancement

#1282 Better End Integration Pass
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/boots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/chests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/helms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/legs.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/gems.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/basic.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/axes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/hoes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/pickaxes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/shovels.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/melee.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/swords.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_growables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/cobbleworks.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
Labels: Maintenance

#1278 Betterend compat
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide_items.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/betterend/alloying.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/betterend/anvil_smithing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/betterend/betterend.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Enhancement

#1290 Add Documentation for Copy-Paste Gadget in the root of the Templates folder
  building_gadgets_patterns/README.txt
Labels: Enhancement

#1294 Abnormals Integration Pass
  config/apotheosis/spawner.cfg
  config/cobblegenrandomizer-common.toml
  config/pneumaticcraft-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crusher.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/integrateddynamics/mechanical_squeezer.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/integrateddynamics/squeezer.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/press.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/chests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/basic.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_dyes.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_sawables.js
  kubejs/server_scripts/enigmatica/kubejs/constants/cobbleworks.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/soils.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: 0.4.0, Maintenance

#1298 added new biomes to conf and set weight to 10 for testing
  config/terraforged/biome_weights.conf
Labels: Maintenance

#1303 Comb recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/press.js
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
Labels: Bug

#1309 Added BYG pollen recipes (block -> item and viceversa)
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#1313 Better End : The Taggening - Add basic tags to many items/blocks from better end
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crusher.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/integrateddynamics/mechanical_squeezer.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/integrateddynamics/squeezer.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/bookshelves.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/workbench.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/betterend/betterend.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/bookshelves.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/dusts.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/fruits.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/gems.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ingots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushroom_caps.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushroom_stems.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/mushrooms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/seeds.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/shards.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/melee.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/workbench.js
Labels: Development

#1319 Tag Maintenance Pass - Clean up Tag Search Scripts
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/boots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/chests.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/helms.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/legs.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bags.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/basic.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bulk.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/energy.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/gases.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/liquids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/axes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/hammers.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/hoes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/multi-tools.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/pickaxes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/shovels.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/melee.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/ranged.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/swords.js
Labels: Maintenance

#1324 Industrial Foregoing Laser Drill - Update Biomes Lists
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_fluid.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
  kubejs/server_scripts/enigmatica/kubejs/constants/biomes.js
Labels: Development

#1325 Tag BYG redstone, Add a few heat sources PNC and Powah
  config/powah/general_common.toml
  kubejs/data/pneumaticcraft/block_heat_properties/byg/cryptic_magma.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/heat_frame_cooling.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ores.js
Labels: Enhancement

#1337 Compact Machines recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/injecting.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/compactcrafting/miniaturization.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mekanism/metallurgic_infusing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/thermal/machine/induction_smelter.js
Labels: Enhancement

#1346 Better End Compat Pass for Latest Update
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ingots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/nuggets.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/seeds.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/axes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/hoes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/pickaxes.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/shovels.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/melee.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/weapons/swords.js
  kubejs/server_scripts/enigmatica/kubejs/constants/biomes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: Development

#1351 Added rftools aliases
  config/morphtool-common.toml
Labels: Maintenance

#1365 Tweak Obsidian Crushing
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
Labels: Development

#1368 Create Menril/Chorus Processing Recipes for Thermal and PneumaticCraft
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/heat_frame_cooling.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/thermo_plant_essence_conversion.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/bottler.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/chiller.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/press.js
Labels: 0.4.0, Enhancement

#1371 Disable Better End Anvils
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/betterend/anvil_smithing.js
Labels: Development

#1376 Adds more mountain oregen
  config/emendatusenigmatica-common.toml
  config/worldstripper-common.toml
Labels: Enhancement

#1375 Update BuildingGadgets' README.txt w/ A Link To DW20's Spotlight
  building_gadgets_patterns/README.txt
Labels: Enhancement

#1378 Added Diet food groups to unsupported mod foods
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/diet/fruits.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/diet/grains.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/diet/proteins.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/diet/sugars.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/diet/vegetables.js
Labels: Enhancement

#1380 Update sugars.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/diet/sugars.js
Labels: Development

#1382 Move Mimiccream to Mimic drop table
  kubejs/data/artifacts/loot_tables/entities/mimic.json
Labels: Enhancement

#1386 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.0.md
Labels: Maintenance

#1405 Imgbot Image compression
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/brass_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/bronze_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/constantan_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/electrum_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/enderium_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/invar_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/lumium_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/signalum_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/metals/steel_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/blaze_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/boobee.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/boobee_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/clay_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/ender_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/ghast_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/glowstone_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/gravel_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/icy_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/obsidian_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/quartz_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/sand_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/water.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/water_angry.png
  packmenu/resources/assets/enigmatica/textures/accessibility.png
  packmenu/resources/assets/enigmatica/textures/bisect.png
  packmenu/resources/assets/enigmatica/textures/discord.png
  packmenu/resources/assets/enigmatica/textures/empty.png
  packmenu/resources/assets/enigmatica/textures/github.png
  packmenu/resources/assets/enigmatica/textures/language.png
  packmenu/resources/assets/enigmatica/textures/logo.png
  packmenu/resources/assets/enigmatica/textures/mods.png
  packmenu/resources/assets/enigmatica/textures/multiplayer.png
  packmenu/resources/assets/enigmatica/textures/options.png
  packmenu/resources/assets/enigmatica/textures/quit.png
  packmenu/resources/assets/enigmatica/textures/singleplayer.png
  packmenu/resources/assets/enigmatica/textures/twitter.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_0.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_1.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_2.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_3.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_4.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_5.png
Labels: Maintenance

#1408 Added tags to backpacks to use in quest hand-ins
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/sophisticatedbackpacks/backpacks.js
Labels: Development

#1428 Lowered artifact rates in end city loot (and accidentally fixed #1391)
  kubejs/data/minecraft/loot_tables/chests/end_city_treasure.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Bug

#1443 Changelogs
  MODLIST.md
  changelogs/CHANGELOG.md
  changelogs/CHANGELOG_MODS_0.4.1.md
Labels: Maintenance

#1454 Updated occultism loot boxes
  kubejs/data/enigmatica/loot_tables/chests/quest_occultism_loot_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_occultism_loot_legendary.json
Labels: Enhancement

#1446 Mekanism Bins and Iron Chests Texture Update
  kubejs/assets/ironchest/textures/item/copper_iron_upgrade.png
  kubejs/assets/ironchest/textures/item/copper_silver_upgrade.png
  kubejs/assets/ironchest/textures/item/diamond_crystal_upgrade.png
  kubejs/assets/ironchest/textures/item/diamond_obsidian_upgrade.png
  kubejs/assets/ironchest/textures/item/gold_diamond_upgrade.png
  kubejs/assets/ironchest/textures/item/iron_gold_upgrade.png
  kubejs/assets/ironchest/textures/item/silver_gold_upgrade.png
  kubejs/assets/ironchest/textures/item/wood_copper_upgrade.png
  kubejs/assets/ironchest/textures/item/wood_iron_upgrade.png
  kubejs/assets/ironchest/textures/model/copper_chest.png
  kubejs/assets/ironchest/textures/model/crystal_chest.png
  kubejs/assets/ironchest/textures/model/diamond_chest.png
  kubejs/assets/ironchest/textures/model/gold_chest.png
  kubejs/assets/ironchest/textures/model/iron_chest.png
  kubejs/assets/ironchest/textures/model/obsidian_chest.png
  kubejs/assets/ironchest/textures/model/silver_chest.png
  kubejs/assets/mekanism/textures/block/bin/advanced_front.png
  kubejs/assets/mekanism/textures/block/bin/advanced_front_on.png
  kubejs/assets/mekanism/textures/block/bin/advanced_side.png
  kubejs/assets/mekanism/textures/block/bin/advanced_side_on.png
  kubejs/assets/mekanism/textures/block/bin/advanced_top.png
  kubejs/assets/mekanism/textures/block/bin/advanced_top_on.png
  kubejs/assets/mekanism/textures/block/bin/basic_front.png
  kubejs/assets/mekanism/textures/block/bin/basic_front_on.png
  kubejs/assets/mekanism/textures/block/bin/basic_side.png
  kubejs/assets/mekanism/textures/block/bin/basic_side_on.png
  kubejs/assets/mekanism/textures/block/bin/basic_top.png
  kubejs/assets/mekanism/textures/block/bin/basic_top_on.png
  kubejs/assets/mekanism/textures/block/bin/bottom.png
  kubejs/assets/mekanism/textures/block/bin/creative_front.png
  kubejs/assets/mekanism/textures/block/bin/creative_front_on.png
  kubejs/assets/mekanism/textures/block/bin/creative_side.png
  kubejs/assets/mekanism/textures/block/bin/creative_side_on.png
  kubejs/assets/mekanism/textures/block/bin/creative_top.png
  kubejs/assets/mekanism/textures/block/bin/creative_top_on.png
  kubejs/assets/mekanism/textures/block/bin/elite_front.png
  kubejs/assets/mekanism/textures/block/bin/elite_front_on.png
  kubejs/assets/mekanism/textures/block/bin/elite_side.png
  kubejs/assets/mekanism/textures/block/bin/elite_side_on.png
  kubejs/assets/mekanism/textures/block/bin/elite_top.png
  kubejs/assets/mekanism/textures/block/bin/elite_top_on.png
  kubejs/assets/mekanism/textures/block/bin/front.png
  kubejs/assets/mekanism/textures/block/bin/front_on.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_front.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_front_on.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_side.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_side_on.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_top.png
  kubejs/assets/mekanism/textures/block/bin/ultimate_top_on.png
Labels: Enhancement

#1466 Add Autumnity/Atmospheric saplings to market
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/atmospheric_saplings.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/autumnity_saplings.json
Labels: Enhancement

#1464 Schematics for the Create Schematicannon
  schematics/AS_astral_relay.nbt
  schematics/AS_attunement_altar.nbt
  schematics/AS_celestial_altar.nbt
  schematics/AS_celestial_gateway.nbt
  schematics/AS_crafting_iridescent_altar.nbt
  schematics/AS_crafting_starlight_altar.nbt
  schematics/AS_enhanced_collector_crystal.nbt
  schematics/AS_evershifting_fountain.nbt
  schematics/AS_ritual_altar.nbt
  schematics/AS_starlight_infuser.nbt
  schematics/IE_arc_furnace.nbt
  schematics/IE_assembler.nbt
  schematics/IE_automated_engineers_workbench.nbt
  schematics/IE_bottling_machine.nbt
  schematics/IE_crusher.nbt
  schematics/IE_diesel_generator.nbt
  schematics/IE_excavator.nbt
  schematics/IE_fermentor.nbt
  schematics/IE_improved_blast_furnace.nbt
  schematics/IE_lightning_rod.nbt
  schematics/IE_metal_press.nbt
  schematics/IE_mixer.nbt
  schematics/IE_refinery.nbt
  schematics/IE_sawmill.nbt
  schematics/IE_silo.nbt
  schematics/IE_squeezer.nbt
  schematics/IE_tank.nbt
  schematics/IP_distillation_tower.nbt
  schematics/IP_pumpjack.nbt
  schematics/MEK_basic_fission_reactor.nbt
  schematics/MEK_basic_fusion_reactor.nbt
  schematics/MEK_basic_industrial_turbine.nbt
  schematics/MEK_basic_sps.nbt
  schematics/MEK_basic_thermal_evap_tower.nbt
  schematics/MEK_basic_thermoelectric_boiler.nbt
  schematics/NA_altar_of_birthing.nbt
  schematics/NA_crimson_altar.nbt
  schematics/NA_natural_altar.nbt
  schematics/README.txt
Labels: Enhancement, Status: Awaiting Information

#1477 Increase IE Crusher ore output back to 2x, plus 10% secondary
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Enhancement

#1473 Added QoL log to chest recipes for all modded logs
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/constants/wood_variants.js
Labels: Enhancement
