Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-11, with the labels that each got.

#3635 Restore Mekanism factory recipes as well as refined obsidian/glowstone
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
Labels: Bug

#3630 [Expert/Normal] Occultism Ritual Updates
  config/ftbquests/quests/chapters/building.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/silver_crushed_ore.png
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/canines.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Development

#3643 0.5.20
  automation/settings.ps1
  config/configswapper/expert/config/Mekanism/machine-storage.toml
  config/configswapper/expert/config/Mekanism/machine-usage.toml
  config/configswapper/expert/config/powah/energy/generators/reactor.toml
  config/configswapper/expert/serverconfig/refinedstorage-server.toml
  config/configswapper/expert/serverconfig/refinedstorageaddons-server.toml
  config/configswapper/expert/serverconfig/rftoolsbuilder-server.toml
  config/configswapper/expert/serverconfig/rsinfinitybooster-server.toml
  config/configswapper/normal/config/Mekanism/machine-storage.toml
  config/configswapper/normal/config/Mekanism/machine-usage.toml
  config/configswapper/normal/config/powah/energy/generators/reactor.toml
  config/configswapper/normal/serverconfig/refinedstorage-server.toml
  config/configswapper/normal/serverconfig/refinedstorageaddons-server.toml
  config/configswapper/normal/serverconfig/rftoolsbuilder-server.toml
  config/configswapper/normal/serverconfig/rsinfinitybooster-server.toml
  config/defaultoptions/options.txt
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/building.snbt
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  config/ftbquests/quests/chapters/industrial_foregoing.snbt
  config/ftbquests/quests/chapters/integrated_dynamics.snbt
  config/ftbquests/quests/chapters/mekanism.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/pedestals.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/powah.snbt
  config/ftbquests/quests/chapters/refined_storage.snbt
  config/ftbquests/quests/chapters/resourceful_bees.snbt
  config/ftbquests/quests/chapters/rftools_wip.snbt
  config/ftbquests/quests/chapters/storage.snbt
  config/ftbquests/quests/chapters/tetra.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/jei/recipe-category-sort-order.ini
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/silver_crushed_ore.png
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/biofuel_crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/biofuel_crushing_tags.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/reaction.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/canines.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/reaction.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mekanism/reaction.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
  minecraftinstance.json
Labels: Development

#3649 fix typo in canines tag
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/canines.js
Labels: Development

#3650 Remove Atum Pumpkin Pie recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#3655 Update Thermal quest descriptions and requirements
  config/ftbquests/quests/chapters/thermal_series.snbt
Labels: Enhancement

#3657 Create Quests - Update titles and quest order of fluid pipe quests
  config/ftbquests/quests/chapters/create.snbt
Labels: Enhancement

#3664 Update the default ultimine config to merge `forge:ores/*`
  defaultconfigs/ftbultimine-server.snbt
Labels: Enhancement

#3665 [Expert] Fix for PNC Progression
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/shaped.js
Labels: Development

#3660 [Expert] Sophisticated Backpacks and Dank/Tank Expertification
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/scented_stick.png
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/dankstorage/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/dankstorage/upgrade.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/farmersdelight/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_anvil_smashing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/sophisticatedbackpacks/backpack_upgrade.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/sophisticatedbackpacks/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tanknull/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tanknull/upgrade.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3674 @Chipped Glowstone + Planks are missing stonecutter recipes.
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#3677 [Expert] Fix for PNC Refinery Progression issue
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
Labels: Development

#3676 [Expert] Flux Networks and Compact Machines
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/fluxnetworks/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/fluxnetworks/shaped.js
Labels: Development

#3672 [Expert] Tweaks
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  defaultconfigs/scannable-server.toml
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/scannable/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/scannable/shapeless.js
Labels: Development

#3684 Remove Powah 'starter' tier from tags to prevent them being shown in quests
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/powah/powah.js
Labels: Enhancement

#3685 Expand Scoria Stonecutting to new BYG types.
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Maintenance

#3687 Add BYG Scoria to Stonecutter
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#3689 [Expert] PNC Lithium Fix
  kubejs/assets/enigmatica/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/refinery.js
Labels: Development

#3691 [Expert] Corundum enhancements
  defaultconfigs/scannable-server.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/block_transmutation.js
Labels: Development

#3696 Fix typo in Astral Sorcery quest
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
Labels: Maintenance

#3695 [Expert] Guns without roses
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/gunswithoutroses/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/gunswithoutroses/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/casting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/casting_table.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/bottler.js
Labels: Development

#3701 [Expert] fix concrete
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crafting_turn_and_copy.js
Labels: Development

#3708 Quest Text Update explaining use of Quark Trees for Ritual of the Forest
  config/ftbquests/quests/chapters/natures_aura.snbt
Labels: Enhancement

#3720 [Expert] Storage Drawers
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/storagedrawers/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/enigmatica/shaped.js
Labels: Development

#3726 [Expert] Misc Tweaks
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/buildinggadgets/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/resourcefulbees/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/shrink/shaped.js
Labels: Development

#3728 Fix Tallow/Leather Conflict in Redstone Furnace
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/blasting.js
Labels: Enhancement

#3729 cured rubber
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/tconstruct/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/tconstruct/casting_basin.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/tconstruct/melting.js
  kubejs/startup_scripts/fluid_registry.js
Labels: Enhancement

#3734 Improve Gunpowder recipes and Add Wandering Traders to Occultism's villager sacrifice tag
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/occultism/humans.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#3559 Mention the `quark:dragon_scale` doesn't drop from the first
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
Labels: Enhancement

#3736 [Expert] IF Progression and IE Part Two
  config/ftbquests/quests/chapters/hidden_quests.snbt
  config/ftbquests/quests/chapters/tech_t3.snbt
  config/gamestages/known_stages.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/advanced_packing_crate_gray.png
  kubejs/assets/kubejs/textures/item/advanced_packing_crate_green.png
  kubejs/assets/kubejs/textures/item/advanced_packing_crate_purple.png
  kubejs/assets/kubejs/textures/item/blueprint.png
  kubejs/assets/kubejs/textures/item/packing_crate_blue.png
  kubejs/assets/kubejs/textures/item/packing_crate_gray.png
  kubejs/assets/kubejs/textures/item/packing_crate_lime.png
  kubejs/assets/kubejs/textures/item/packing_crate_orange.png
  kubejs/assets/kubejs/textures/item/packing_crate_red.png
  kubejs/assets/kubejs/textures/item/packing_crate_yellow.png
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_1_starlight.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/farmersdelight/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/amadron.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/industrialforegoing/shaped.js
  kubejs/startup_scripts/item_registry.js
  kubejs/startup_scripts/multiblock_gamestages.js
Labels: Development

#3742 [Expert] IE Crusher buff
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/expert/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/normal/unification/unify_materials.js
Labels: Development

#3636 Add Tinkers Construct Quest Line and Loot Tables
  config/ftbquests/quests/chapters/tinkers_construct.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/common_lootbox.png
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_common.json
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_legendary.json
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_rare.json
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#3749 [Expert] IF Machine Shuffle
  config/cobblegenrandomizer-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
Labels: Development

#3761 Valhelsia: Add recipes for dungeon door and cut wood posts
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/valhelsia_structures/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/valhelsia_structures/shapeless.js
Labels: Enhancement

#3757 [Expert] Aura Generation Tweak
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
Labels: Development

#3764 [Expert] Feedback Tweaks
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/engineersdecor/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/blueprint.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/spirit_fire.js
Labels: Development

#3768 Add JEI Descriptions for obtaining Enderiophage and summoning the Void Worm
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
Labels: Enhancement

#3765 Many More Bees
  changelogs/CHANGELOG.md
  config/resourcefulbees/bee_traits/sedimentary.json
  config/resourcefulbees/bee_traits/slippers.json
  config/resourcefulbees/bees/magic/Carbee.json
  config/resourcefulbees/bees/magic/Otherworldly.json
  config/resourcefulbees/bees/material/Shepherd.json
  config/resourcefulbees/bees/metal/Frosty.json
  config/resourcefulbees/bees/metal/Regal.json
  config/resourcefulbees/bees/natural/Brutish Zombee.json
  config/resourcefulbees/bees/natural/Clogged.json
  config/resourcefulbees/bees/natural/Forest.json
  config/resourcefulbees/bees/special/Boobee.json
  config/resourcefulbees/bees/special/Dusty_Mummbee.json
  config/resourcefulbees/bees/tech/PCBee.json
  config/resourcefulbees/honey/Mana.json
  config/resourcefulbees/honey/Otherworldly.json
  config/resourcefulbees/honey/illuminating.json
  config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/carbee.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/carbee_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/clogged.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/clogged_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/dusty_mummbee.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/dusty_mummbee_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/frosty.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/frosty_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/otherworldly.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/otherworldly_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/regal.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/regal_angry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/shepherd.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/shepherd_angry.png
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/atum/chests/pharaoh.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/hive_upgrade_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/bees.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/meats.js
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#3772 [Expert] Turntable Fix
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/shaped.js
Labels: Development

#3782 Update base/RBees/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/shaped.js
Labels: Maintenance

#3770 Brutish Zombee Boss
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/apotheosis/bosses.js
Labels: Enhancement

#3790 Fix Powah chapters, revert Tag change
  config/ftbquests/quests/chapters/powah.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/powah/powah.js
Labels: Enhancement

#3793 Fix typo in storage drawer script
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/storagedrawers/shaped.js
Labels: Development

#3794 Fix Typo in Create Infinite Fluid Pumping blacklist. Clarify Logic Circuit description.
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/create/no_infinite_draining.js
Labels: Bug

#3796 fix flare stack recipe
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersivepetroleum/shaped.js
Labels: Development

#3799 [Expert] Slime Boots
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/washables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/shaped.js
Labels: Development

#3788 Apotheosis Tome Towers and Astral Shrines loot tweaks
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/apotheosis/tome_tower.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/astralsorcery/shrine_chest.js
Labels: Enhancement

#3805 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/fr_fr.json
  kubejs/assets/enigmatica/lang/sv_se.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/tetra/lang/sv_se.json
Labels: Enhancement

#3809 [Expert] Makes mek bins slightly more expensive
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mekanism/shaped.js
Labels: Development

#3813 [Expert] Quest Tweaks
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/magic__adept.snbt
  config/ftbquests/quests/chapters/magic__master.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/startup_scripts/item_registry.js
Labels: Development
