Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-12, with the labels that each got.

#3807 Move Alloy Bees to Induction Smelter
  config/resourcefulbees/bees/alloy/Brass.json
  config/resourcefulbees/bees/alloy/Bronze.json
  config/resourcefulbees/bees/alloy/Constantan.json
  config/resourcefulbees/bees/alloy/Electrum.json
  config/resourcefulbees/bees/alloy/Enderium.json
  config/resourcefulbees/bees/alloy/Invar.json
  config/resourcefulbees/bees/alloy/Lumium.json
  config/resourcefulbees/bees/alloy/Signalum.json
  config/resourcefulbees/bees/alloy/Steel.json
  config/resourcefulbees/bees/metal/Gold.json
  config/resourcefulbees/bees/metal/Iron.json
  config/resourcefulbees/bees/metal/Nickel.json
  config/resourcefulbees/bees/metal/Silver.json
  config/resourcefulbees/bees/metal/Tin.json
  config/resourcefulbees/bees/metal/Zinc.json
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Maintenance

#3817 [Expert] Create Swim Gear update and extra loots
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/apotheosis/tome_tower.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/astralsorcery/shrine_chest.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/underwater_treasure_additions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/shaped.js
Labels: Development

#3821 [Expert] Pyrolizer back behind coke dust
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/replace_input.js
Labels: Development

#3823 [Expert] Smol Tweaks
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/block_transmutation.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/scannable/shaped.js
Labels: Development

#3826 Little Buzzy Tweaks
  config/resourcefulbees/bees/metal/Frosty.json
  config/resourcefulbees/bees/natural/Creeper.json
  config/resourcefulbees/bees/natural/Forest.json
  config/resourcefulbees/bees/natural/Pigman.json
  config/resourcefulbees/bees/natural/RGBee.json
  config/resourcefulbees/bees/natural/Sand.json
  config/resourcefulbees/bees/natural/Skeleton.json
  config/resourcefulbees/bees/natural/Slimy.json
  config/resourcefulbees/bees/natural/Zombie.json
  kubejs/data/enigmatica/loot_tables/chests/quest_resourceful_bees_loot_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_resourceful_bees_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/chests/quest_resourceful_bees_loot_rare.json
Labels: Maintenance

#3829 Atum - Bringing some life
  config/alexsmobs/bald_eagle_spawns.json
  config/alexsmobs/crocodile_spawns.json
  config/alexsmobs/emu_spawns.json
  config/alexsmobs/fly_spawns.json
  config/alexsmobs/gazelle_spawns.json
  config/alexsmobs/guster_spawns.json
  config/alexsmobs/komodo_dragon_spawns.json
  config/alexsmobs/rattlesnake_spawns.json
  config/alexsmobs/roadrunner_spawns.json
  config/alexsmobs/sunbird_spawns.json
  config/alexsmobs/tarantula_hawk_spawns.json
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/apotheosis/tome_tower.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/atum/chests/crate.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/atum/chests/pharaoh.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/atum/chests/pyramid_chest.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/underwater_treasure_additions.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/minecraft/entities.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/alexsmobs/spawn_blocks.js
Labels: Enhancement

#3835 Fix Enchanting Apparatus not accepting tools as input
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Bug

#3836 [Expert] Progression fixes, quests
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/powah.snbt
  config/ftbquests/quests/chapters/tetra.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
Labels: Development

#3837 Unify Mud types, add mud bricks to block cutter
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#3839 script cleanup
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ironjetpacks/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/shaped.js
Labels: Maintenance

#3842 [Expert] More tweaks
  config/ftbquests/quests/chapters/magic__adept.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/elven_trade.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/minecraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/shaped.js
Labels: Development

#3845 Documentation and tweaks
  config/ftbquests/quests/chapters/tools.snbt
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/atum/chests/crate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
Labels: Development

#3846 Quark Gold Bars may now be melted for gold nuggets.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
Labels: Enhancement

#3854 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/cs_cz.json
  kubejs/assets/enigmatica/lang/zh_tw.json
  kubejs/assets/kubejs/lang/zh_tw.json
  kubejs/assets/tconstruct/lang/zh_tw.json
  packmenu/resources/assets/enigmatica/lang/zh_tw.json
Labels: Enhancement

#3860 Fix uncraftable Tinkers parts using Thermal materials. Clean up unused materials.
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/item_modifiers/jei_hide_fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/casting_basin.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/materials.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/tconstruct/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/tconstruct/casting_basin.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/tconstruct/melting.js
Labels: Enhancement

#3863 [Expert] fix broken dank upgrades
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/dankstorage/upgrade.js
Labels: Development

#3867 [Expert] Convert CPU crafting to Assembly Table crafting
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3871 [Expert] Infinity Tools
  config/ftbquests/quests/chapters/magic__master.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/betterend/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
Labels: Development

#3873 [Expert] Glyph updates to give an easier path to silk touch
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/glyph_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_0_luminous.js
Labels: Development

#3874 [Expert] Tinkers and Mek armor update
  config/configswapper/expert/config/Mekanism/gear.toml
  config/configswapper/normal/config/Mekanism/gear.toml
  config/scannable-client.toml
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3897 Remove certus quartz from IF miner
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#3898 [Expert] Tier 3 magic quests and progression tweaks
  config/ftbquests/quests/chapters/magic__adept.snbt
  config/ftbquests/quests/chapters/magic__master.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/block/loot_tables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/loot_tables/block/disabled_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_2_celestial.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/rune_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3899 Fix Tinker's Anvil quest to accept any Tinker's Anvil
  config/ftbquests/quests/chapters/tinkers_construct.snbt
Labels: Enhancement

#3903 Update PNC quests to be compatible with Expert
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
Labels: Development

#3599 [Expert] IE Energy tweaks
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  config/configswapper/expert/serverconfig/immersivepetroleum-server.toml
  config/configswapper/normal/serverconfig/immersiveengineering-server.toml
  config/configswapper/normal/serverconfig/immersivepetroleum-server.toml
  defaultconfigs/immersiveengineering-server.toml
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/fertilizer.js
Labels: Development

#3907 [Expert] Progression fixes
  config/configswapper/expert/serverconfig/occultism-server.toml
  config/configswapper/normal/serverconfig/occultism-server.toml
  config/ftbquests/quests/chapters/magic__adept.snbt
  defaultconfigs/occultism-server.toml
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/apes.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/petal_apothecary.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/rune_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/fluid_mixer.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3909 [Expert] Typo with heavy machinery schematics
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/amadron.js
Labels: Development

#3910 Fix recipe errors in refactored rituals
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#3911 Re-instate decay removal for spirits after re-factor
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Development

#3912 Use banana tag instead of fixed banana. Maybe the Librarian isn't -that- picky.
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#3913 [Expert] Tech Progression Quests
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  config/ftbquests/quests/chapters/tech_t3.snbt
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/prettypipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/prettypipes/shapeless.js
Labels: Development

#3923 [Expert] Quest updates and other tweaks
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/magic__adept.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  config/ftbquests/quests/chapters/tech_t3.snbt
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/numismatic.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Development

#3933 starter tier showing up in expert powah upgrades. removed.
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/shaped.js
Labels: Development

#3936 [Expert] Update Engineering Student Supplies
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
Labels: Development

#3938 [Expert] Minor fixes
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/tinkers_construct.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
Labels: Development

#3942 Blacklist Atum Pharaoh from spawners (Drygmy)
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/mob_spawner_blacklist.js
Labels: Bug
