Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-10, with the labels that each got.

#3355 Building Quest Chapter Initial Layout
  config/ftbquests/quests/chapters/building.snbt
Labels: Enhancement

#3360 update to rid's quests
  config/ftbquests/quests/chapters/building.snbt
Labels: Development

#3361 Fix Broken Recipe ID
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_2_celestial.js
Labels: Development

#3362 [New Quests!] Building Quest Chapter
  config/ftbquests/quests/chapters/building.snbt
Labels: Enhancement

#3368 Add Blazing Blood as fuel for the Magmatic Dynamo
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/magmatic.js
Labels: Enhancement

#3371 refactor thermal fuel scripts
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/compression.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/lapidary.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/magmatic.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/dynamo/numismatic.js
Labels: Development

#3303 [Expert] Thermal Augments
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/dynamo_fuel_augment.png
  kubejs/assets/kubejs/textures/item/dynamo_output_augment.png
  kubejs/assets/kubejs/textures/item/machine_speed_augment.png
  kubejs/client_scripts/item_modifiers/jei_add_items.js
  kubejs/client_scripts/item_modifiers/jei_add_subtypes.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/pulverizer_catalyst.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/smelter_catalyst.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#3374 Remove Ender Slime as sap output for Green slime saplings. Moved to Pythandron logs instead.
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
Labels: Bug

#3386 add missing glowshrooms to vanilla nether shrooms
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
Labels: Enhancement

#3606 Add Sushigo Crafting items to Compost Bin
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/compote/composting.js
Labels: Enhancement

#3613 Add Missing Simple Farming seeds to Market
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/simplefarming_seeds.json
Labels: Enhancement

#3614 Add Warning to Tetra Quests concerning End Rod Handles
  config/ftbquests/quests/chapters/tetra.snbt
Labels: Enhancement

#3615 Blacklist disabled food items from Spice of Life
  defaultconfigs/solcarrot-server.toml
Labels: Enhancement

#3609 [Expert] Mining Gadgets and other tweaks
  config/configswapper/expert/config/mininggadgets-common.toml
  config/configswapper/normal/config/mininggadgets-common.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mininggadgets/shaped.js
Labels: Development

#3620 Correct Typo in Clay Bee, Correct invalid recipe override for Clay in Alchemy Table
  config/resourcefulbees/bees/material/Clay.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
Labels: Bug
