Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-07, with the labels that each got.

#2597 Add Bee Recipes to MythBot Mana Infuser
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/mythicbotany_infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mythicbotany/infusion.js
Labels: Maintenance

#2588 Fix Curing Rubber take sulfur gems when most recipes produce sulfur dust
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
Labels: Enhancement

#2599 Re-add Green and Brown Dye Mixing Recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#2615 readded citadel, removed soggy's gun..
  minecraftinstance.json
Labels: Development

#2610 Starry Bee color changes
  config/resourcefulbees/bees/magic/Starry.json
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/starry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/starry_angry.png
Labels: Enhancement

#2616 0.5.4
  .gitignore
  automation/.build.json
  automation/modpack-uploader.ps1
  automation/settings.ps1
  config/resourcefulbees/bees/magic/Starry.json
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/starry.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/starry_angry.png
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  local/ftbchunks/client-config.snbt
  minecraftinstance.json
Labels: Development

#2630 Refactor shaped.js - Normal
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/botania/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/compactcrafting/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/eidolon/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/minecraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/mythicbotany/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/prettypipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/quark/shaped.js
Labels: Development

#2628 Unify Tree Fluid Outputs
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/farmersdelight/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/fluid_extractor.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/tree_extractor.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
  kubejs/server_scripts/enigmatica/kubejs/functions.js
Labels: Enhancement

#2644 Update animals.js
  kubejs/server_scripts/enigmatica/kubejs/constants/animals.js
Labels: Maintenance

#2646 Cleanup curios inventory
  defaultconfigs/curios-server.toml
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/curios/bracelet.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/curios/glasses.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/curios/goggles.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/curios/hands.js
Labels: Maintenance

#2664 Updates to Sawing and Crushing - Expanding Occultism, Create, and Immersive Engineering capabilities
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_dyes.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_sawables.js
Labels: Enhancement

#2665 Fix Sawdust recipes for Sawdust flooring and block
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Enhancement

#2671 General Quest Updates: Mekanism and Ars Nouveau
  config/ftbquests/quests/chapters/adventure.snbt
  config/ftbquests/quests/chapters/apotheosis.snbt
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/building.snbt
  config/ftbquests/quests/chapters/challenges.snbt
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/gates_wip.snbt
  config/ftbquests/quests/chapters/getting_started.snbt
  config/ftbquests/quests/chapters/hidden_quests.snbt
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  config/ftbquests/quests/chapters/industrial_foregoing.snbt
  config/ftbquests/quests/chapters/integrated_dynamics.snbt
  config/ftbquests/quests/chapters/mekanism.snbt
  config/ftbquests/quests/chapters/modular_routers.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/pedestals.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/powah.snbt
  config/ftbquests/quests/chapters/refined_storage.snbt
  config/ftbquests/quests/chapters/resourceful_bees.snbt
  config/ftbquests/quests/chapters/rftools_wip.snbt
  config/ftbquests/quests/chapters/storage.snbt
  config/ftbquests/quests/chapters/tetra.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/ftbquests/quests/chapters/tools.snbt
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
Labels: Enhancement

#2672 Quest Updates: Mekanism and Loot Tables
  config/ftbquests/quests/chapters/mekanism.snbt
  kubejs/data/enigmatica/loot_tables/chests/quest_scavengers_delight.json
Labels: Enhancement

#2674 Quest Updates: Immersive Engineering
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  schematics/IE_coker.nbt
  schematics/IE_sulfur_recovery_unit.nbt
Labels: Enhancement

#2675 Blacklist tinker's construct from supplementaries wall lantern support
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  config/supplementaries-common.toml
Labels: Enhancement

#2676 Increase base height of PNC Elevators
  config/pneumaticcraft-common.toml
Labels: Enhancement

#2679 Interactio Fluid interaction for Driftwood now requires multiple logs to complete.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/interactio/item_fluid_transform.js
Labels: Enhancement

#2680 Corrections to Ars Nouveau quests
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Development

#2681 more ars quest adjustments
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Development

#2682 Create Initial Blacklist for Drygmies - Blacklisting mobs already disallowed in other spawners
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/drygmy_blacklist.js
Labels: Enhancement

#2687 Alternate PNC Recipes: Elevator Frames and Canon Barrels
  kubejs/assets/mythicbotany/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/assembly.js
Labels: Enhancement

#2701 Adjustments to Miner's Delight rewards, Structure changes to Create quests
  config/ftbquests/quests/chapters/create.snbt
  kubejs/data/enigmatica/loot_tables/chests/quest_miners_delight.json
Labels: Enhancement

#2702 Make nether ores properly nether only in IF laser drill. Add Cobalt to Dimensional Mineshaft for real this time.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_ores.js
Labels: Enhancement

#2663 Eidolon: clarify the need to find a witch and not a swamp in the first quest
  config/ftbquests/quests/chapters/eidolon_wip.snbt
Labels: Maintenance

#2709 Increase mana cost for Drygmy and Sylph production
  config/ars_nouveau-common.toml
Labels: Enhancement

#2719 Make Post Box craftable earlier
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Enhancement

#2720 [Expert] Make Hovering Hourglass available earlier in progression
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/shaped.js
Labels: Development

#2722 Special Bees spawn chance increase
  config/resourcefulbees/bees/special/Boobee.json
  config/resourcefulbees/bees/special/Clockwork.json
  config/resourcefulbees/bees/special/Soup.json
  config/resourcefulbees/bees/special/Spelling.json
Labels: Enhancement

#2727 [Expert] Botania Tweaks
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/betterend/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/terra_plate.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/infusion.js
Labels: Development

#2741 Fix recipe bleed into Normal
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/custom.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
Labels: Development

#2737 [Expert] More Botania tweaks, some continuation of Blood Magic, and Starting Pedestals
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/infusion.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pedestals/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/casting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/induction_smelter.js
Labels: Development

#2747 [Expert] Pedestal Upgrade Recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/glyph_recipe.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
Labels: Development

#2750 Mekanism Quest updates: Add info about tag filters to Digital Miner
  config/ftbquests/quests/chapters/mekanism.snbt
Labels: Enhancement

#2754 [Expert] Moar Pedestals!!!
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Development

#2753 Wasabee Implementation
  config/resourcefulbees/bees/special/Wasabee.json
  config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/wasabee.png
  config/resourcefulbees/resources/assets/resourcefulbees/textures/entity/other/wasabee_angry.png
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/shaped.js
Labels: Enhancement

#2757 More Typos
  config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json
Labels: Maintenance

#2779 Correctly expand Create and IE sawing
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_sawables.js
Labels: Enhancement

#2782 Fix Nether Wart Outputs from IE Crusher and BM Alchemy
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/crusher.js
Labels: Enhancement

#2783 Add proper tags to Archwood Button
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/minecraft/wooden_buttons.js
Labels: Enhancement

#2784 Fix for some workbenches not being seen as workbenches.
  kubejs/data/rftoolscontrol/recipes/workbench.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/workbench.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/workbench.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/astralsorcery/block_transmutation.js
Labels: Enhancement

#2785 Re add workbench tag
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/workbench.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/workbench.js
Labels: Development

#2787 Re-add ingot to alloy heated mixing
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
Labels: Enhancement

#2788 Add a dark purple tooltip to wither immune blocks
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/client_scripts/normal/item modifiers/tooltips.js
Labels: Enhancement

#2797 Remove Snow > Dense snow in Pressure Chamber
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/pressure_chamber.js
Labels: Enhancement

#2802 Update title to Interfaces quest
  config/ftbquests/quests/chapters/create.snbt
Labels: Development

#2805 Implement crushing multiplier blacklist to prevent dupes, expand Occultism Crushing compat
  kubejs/data/tetra/loot_tables/actions/geode.json
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/tetra/actions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/compound/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/compound/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/functions.js
Labels: Enhancement

#2760 [Expert] Mid game relief recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mixing.js
Labels: Development

#2809 Add EE and KJS fluids to Create Pump Blacklist
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/create/no_infinite_draining.js
Labels: Enhancement

#2818 Add Infinity Nuke nucleosynthesis recipe. Watch out!
  config/ftbquests/quests/chapters/challenges.snbt
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/nucleosynthesizing.js
Labels: Enhancement

#2819 Add Infinity Launcher recipe and quest!
  config/ftbquests/quests/chapters/challenges.snbt
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/nucleosynthesizing.js
Labels: Enhancement

#2829 Add more fun loot to Towers of the Wild
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/towers_of_the_wild/ocean_tower_chest.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/towers_of_the_wild/tower_chest.js
Labels: Enhancement

#2839 Create Sequenced Assembly Script
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber.js
Labels: Maintenance

#2841 JEI description contradition for the `bottle of time`
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
Labels: Development

#2843 0.5.8
  automation/settings.ps1
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber.js
  minecraftinstance.json
Labels: Development

#2858 Tag Update: Adds Chipped, Chisel, and Architect's Palette to valid apiary, and many more
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/basic.js
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
Labels: Enhancement
