Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2021-04, with the labels that each got.

#1903 Add Refined Glowstone to Thermal Series Induction Smelter
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Enhancement

#1904 Add Elemental Rod processing to Mekanism Enrichment Chamber
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/enriching.js
Labels: Enhancement

#1905 Fix missing Wire Coil Recipes
  kubejs/server_scripts/enigmatica/kubejs/normal/unification/unify_materials.js
Labels: Maintenance

#1910 Tree Enhancements
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/refinery.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/tree_extractor.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/tree_extractor_boost.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/fertilizer.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
Labels: Enhancement

#1907 Make Botany Pots and Terracotta washable and Botany Pots re-dyeable and other improvements
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/dissolution_chamber_essence_conversion.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/injecting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/botanypots/botany_pots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/washables.js
Labels: Enhancement

#1930 Iron Jetpacks Update
  config/ironjetpacks/jetpacks/blazing.json
  config/ironjetpacks/jetpacks/diamond.json
  config/ironjetpacks/jetpacks/enderium.json
  config/ironjetpacks/jetpacks/hardened.json
  config/ironjetpacks/jetpacks/invar.json
  config/ironjetpacks/jetpacks/iron.json
  config/ironjetpacks/jetpacks/lumium.json
  config/ironjetpacks/jetpacks/niotic.json
  config/ironjetpacks/jetpacks/nitro.json
  config/ironjetpacks/jetpacks/signalum.json
  config/ironjetpacks/jetpacks/spirited.json
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
Labels: Development

#1937 Update Pedestal Quests
  config/ftbquests/quests/chapters/pedestals.snbt
Labels: Enhancement

#1954 Zoology challenges
  config/ftbquests/quests/chapters/challenges.snbt
  kubejs/assets/enigmatica/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/advancements/husbandry.js
  kubejs/server_scripts/enigmatica/kubejs/constants/animals.js
Labels: Enhancement

#1961 Add Missing Yellow Blossoms to dyes pool and missing Tremblecrust to randomizer
  config/cobblegenrandomizer-common.toml
  kubejs/server_scripts/enigmatica/kubejs/constants/cobbleworks.js
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
Labels: Maintenance

#1971 Host of minor integrations additions
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/botania/pure_daisy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/metallurgic_infusing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/block_heat_properties.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/press.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/rods.js
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
Labels: Development

#1985 Minor refactoring of create mechanical crafting recipes.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/mechanical_crafting.js
Labels: Development

#1989 Quest Maintenance
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/refined_storage.snbt
  config/ftbquests/quests/chapters/tools.snbt
Labels: Maintenance

#2009 Powah QOL Crafting for upgrading Reactors, Cables, and Ender Gates
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#2016 Undergarden Crop update - fix broken Ditchbulb reference
  kubejs/server_scripts/enigmatica/kubejs/constants/crops.js
Labels: Maintenance

#2018 Update to Lights and Bags search tags
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/lights.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bags.js
Labels: Maintenance

#2019 Ars Nouveau Quest Updates - Potion Crafting
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Maintenance

#2023 Better End Compat - add Ingot > Nugget recipe. Remove excess Jaopca blocks for Better End Metals
  config/jaopca/modules/storage_blocks.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Maintenance

#2032 Changelogs Mostly
  MODLIST.md
  automation/modpack-uploader.ps1
  changelogs/CHANGELOG.md
  changelogs/changelog_mods_0.4.9.md
  changelogs/modlist_0.4.9.md
  github-changelog-generator.bat
  server_files/server-setup-config.yaml
Labels: Maintenance

#2036 Update Valid_Apiaries
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
Labels: Enhancement

#2038 DungeonCrawl Winner Dungeons: Initial Loot Table Creation
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/dungeon_loot_tables.js
Labels: Development

#2041 Wandering Trader Armor Trade Tweaks: Nerfs Levels and Adds Variety
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/apotheosis/wandering_trader_trades.js
Labels: Enhancement

#2042 Remove the need for the Ars Nouveau glyph recipe, use a not filter in…
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/ars_nouveau/glyph_recipe.js
Labels: Development

#2045 Sync GitHub template change
  .github/ISSUE_TEMPLATE/config.yml
Labels: Maintenance

#2052 Pressure Chamber Wheat Recipe Override
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/explosion.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/fuels.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/pressure_chamber.js
Labels: Development

#2066 Compact Machine Crafting Fix and Quests to Introduce Them
  config/ftbquests/quests/chapters/storage.snbt
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/compactcrafting/miniaturization.js
Labels: Maintenance
