Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-07, with the labels that each got.

#5051 glowstone melting and Tritium clarification
  config/ftbquests/quests/chapters/tech_t3.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
Labels: Enhancement

#5050 [Expert] Mastery Shard Tweaks
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_2_celestial.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/auto_iridescent_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/sawmill.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#5053 [Expert] Alchemy Mastery Shard Update
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/atum/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#5061 [Expert] Fix Colored Botany Pot recipe
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
Labels: Enhancement

#5059 Cleanup - Disable unused compact crafting, remove quests about them
  config/ftbquests/quests/chapters/storage.snbt
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Development

#5071 [Normal] Moonstone Recipe
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/botania/mana_infusion.js
Labels: Enhancement

#5077 Increase mana capacity of the Gaia Reactor
  config/masterful_machinery/controllers/gaia_reactor.json
Labels: Enhancement

#5078 [Expert] Fix visibility for Bragging Rights chapter
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
Labels: Bug

#5086 New Crowdin updates
  kubejs/assets/enigmatica/lang/pt_br.json
  kubejs/assets/ponderjs/lang/pt_br.json
  kubejs/assets/tconstruct/lang/pt_br.json
Labels: Enhancement

#5102 [Expert] Speed increases
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  config/configswapper/normal/serverconfig/immersiveengineering-server.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/unification/unify_materials.js
Labels: Enhancement

#5106 Convert to using PNC's entity blacklist tag instead of old config system
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/pneumaticcraft/vacuum_trap_blacklist.js
Labels: Enhancement

#5107 Update Iesnium pick melting to reflect expert cost
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/melting.js
Labels: Enhancement

#5105 New Crowdin updates
  kubejs/assets/kubejs/lang/ru_ru.json
Labels: Enhancement

#5109 [Expert] Add direct craft for Forgotten tools
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/undergarden/shaped.js
Labels: Enhancement
