Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-05, with the labels that each got.

#4745 Remove cheesy Pharaoh spawning
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/rftoolsutility/spawner.js
Labels: Enhancement

#4753 Lens of ender alternate
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/compacting.js
Labels: Enhancement

#4754 Disable Wire Melting dupe loop
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#4756 Add Crafting Recipe for Sand Layers
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/atum/shaped.js
Labels: Enhancement

#4757 Convert powah recipes to integers
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/energizing.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/powah/energizing.js
Labels: Enhancement

#4759 Allow completion of Powah quests in Expert
  config/ftbquests/quests/chapters/powah.snbt
Labels: Enhancement

#4736 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/nl_nl.json
  kubejs/assets/kubejs/lang/zh_cn.json
Labels: Enhancement

#4767 Add crushing recipes for Aquamarine
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/crushing.js
Labels: Enhancement

#4768 Convert Wicked Altar recipes to consume entire blood amount up front.
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/wicked_altar.js
Labels: Enhancement

#4770 Fix More recipes that were in the wrong spot
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/prettypipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/prettypipes/shapeless.js
Labels: Enhancement

#4763 [Expert] LP and Liquid Starlight Improvements Part Two
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_fluid.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/lightwell.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/laser_drill_fluid.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/industrialforegoing/laser_drill_fluid.js
Labels: Enhancement

#4777 Removed commas from apo spawner blacklist
  config/apotheosis/spawner.cfg
Labels: Bug

#4778 [Expert] Laputian Ingot fix
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/petal_apothecary.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
Labels: Enhancement

#4791 Add `blazing blood` to the `fluid laser`
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/laser_drill_fluid.js
Labels: Enhancement

#4794 [Expert] Reduce cost of Ethereal Slates
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
Labels: Enhancement

#4797 Fix Tinker's Broad Axe quest requirements
  config/ftbquests/quests/chapters/tinkers_construct.snbt
Labels: Enhancement

#4798 [Expert] Add Brine and Lithium recipes to IP's Distillation Tower
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/distillation.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/oilcracking.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersivepetroleum/distillation.js
Labels: Enhancement

#4799 Replace IP's Lubricant with PNC's
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/distillation.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
Labels: Enhancement

#4796 [Expert] Alternate recipe for Graphite
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/enriching.js
Labels: Enhancement

#4800 [Expert] Alterations to Occultism Ritual outputs
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/enderstorage/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/modularrouters/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/storagedrawers/shaped.js
Labels: Enhancement

#4803 Betterend ore automation
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_ore.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/ores.js
Labels: Enhancement

#4808 [Expert] Change Flux Networks gate to put it behind mekanism properly
  config/ftbquests/quests/chapters/gates_wip.snbt
Labels: Enhancement

#4801 [Expert] Recycle Powah Reactors
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
Labels: Enhancement

#4810 [Expert] Update to the slates used to make circuits cheaper
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
Labels: Enhancement

#4815 Tinkers Transform Recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/shapeless.js
Labels: Maintenance

#4813 [Expert] Re-balance aura recipes
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
Labels: Enhancement

#4818 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/ru_ru.json
Labels: Enhancement

#4823 [Expert] Improve RS Storage by skipping the first two tiers of disks
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/refinedstorage/shapeless.js
Labels: Enhancement

#4831 fairer storage parts upgrades
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/refinedstorage/shapeless.js
Labels: Development

#4821 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/ru_ru.json
  kubejs/assets/enigmatica/lang/ru_ru.json
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
  kubejs/assets/ponderjs/lang/ru_ru.json
  kubejs/assets/tconstruct/lang/ru_ru.json
  kubejs/assets/tetra/lang/ru_ru.json
Labels: Enhancement

#4832 Modify DIY Mek recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
Labels: Bug

#4840 [Expert] Make cloches only accept simple botany pots to clarify their place in progression
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
Labels: Enhancement

#4841 New Crowdin updates
  kubejs/assets/enigmatica/lang/ru_ru.json
Labels: Enhancement

#4846 New Crowdin updates
  kubejs/assets/enigmatica/lang/ru_ru.json
Labels: Enhancement

#4845 [Expert] Better progression for cloche, insolator, and botany pots
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
Labels: Enhancement

#4848 Update Seared Melter quest to make it a little more clear how to complete in Expert
  config/ftbquests/quests/chapters/tinkers_construct.snbt
Labels: Enhancement

#4844 Allow upgrading black hole units/tanks
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smithing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
Labels: Enhancement

#4847 New Crowdin updates
  kubejs/assets/enigmatica/lang/ru_ru.json
Labels: Enhancement

#4849 [Expert] Replace CPU Cores with new custom art
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/advanced_ram_chip.png
  kubejs/assets/kubejs/textures/item/cpu_core_as_81221.png
  kubejs/assets/kubejs/textures/item/cpu_core_eg_28222.png
  kubejs/assets/kubejs/textures/item/cpu_core_mk_1026.png
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/computercraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/refinedstorage/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#4854 New Crowdin updates
  kubejs/assets/enigmatica/lang/ru_ru.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/ponderjs/lang/ru_ru.json
  kubejs/assets/tconstruct/lang/ru_ru.json
  kubejs/assets/tetra/lang/ru_ru.json
Labels: Enhancement

#4867 [Expert] Allow mixing Pink Enderslime with PNC
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/fluid_mixer.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/industrialforegoing/shaped.js
Labels: Enhancement

#4872 Include downloadUrl in future manifest files
  automation/modpack-uploader.ps1
  server_files/start-server.bat
  server_files/start-server.sh
  server_files_expert/start-server.bat
  server_files_expert/start-server.sh
Labels: Enhancement

#4876 [Expert] Rename CPU assembly packages to match the output
  kubejs/assets/kubejs/lang/en_us.json
Labels: Enhancement

#4877 New Crowdin updates
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
Labels: Enhancement

#4891 [Expert] Fix typo preventing alternate assembly controller recipe from showing in game.
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
Labels: Enhancement

#4894 Create Tip for Well of Suffering/NoAI Spawners
  kubejs/assets/enigmatica/tips/well_of_suffering.json
Labels: Enhancement

#4904 Many fixes for packing and unpacking with Thermal and Immersive Engineering
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/packing_unpacking.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/thermal/dies.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/metal_press.js
Labels: Enhancement

#4896 [Expert] Buff the IP Coker
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/coker.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/coking.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/distillation.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/hydrotreater.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersivepetroleum/reservoirs.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersivepetroleum/coker.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersivepetroleum/distillation.js
Labels: Enhancement

#4907 Port irradiated miner to normal
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/irradiated.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/dimensional_mineshaft/irradiated.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
Labels: Enhancement

#4906 Update Astral Wood Recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/astralsorcery/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/sawmill.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
Labels: Enhancement

#4915 Remove extra bottling recipes for XP.
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/bottler.js
Labels: Enhancement

#4918 Fix missing ingot tags on several ingots
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ingots.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js
Labels: Enhancement

#4919 Fix missing Nugget tags
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/nuggets.js
Labels: Enhancement

#4921 Update Akashic Tome in Quests
  config/ftbquests/quests/chapters/getting_started.snbt
Labels: Maintenance

#4924 LP Buff
  config/apotheosis/spawner.cfg
  config/bloodmagic-common.toml
Labels: Enhancement

#4923 Port Stellar Neutron Activator and Industrial Deuterium Plant to Normal mode
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/masterful_machinery/industrial_deuterium_plant.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/masterful_machinery/stellar_neutron_activator.js
Labels: Enhancement

#4920 [Expert] Better yield from nucleosynthesizing
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/nucleosynthesizing.js
Labels: Enhancement

#4927 Update Enchanting Bonuses for Apotheosis
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/apotheosis/enchanting_stats.js
  kubejs/server_scripts/enigmatica/kubejs/constants/atum_aspects.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/apotheosis/enchanting_stats.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/minecraft/shaped.js
Labels: Enhancement

#4933 fix for tag failures in new enchanting stats
  kubejs/server_scripts/enigmatica/kubejs/constants/bookshelves.js
  kubejs/server_scripts/enigmatica/kubejs/constants/candles.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/apotheosis/enchanting_stats.js
Labels: Development

#4934 Blast Chiller Updates
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/chiller.js
Labels: Enhancement

#4935 `ci` list infinite fluids
  .github/actions/ci/kubejs-list-hose-pulley-fluids.js
  .github/actions/ci/log-kubejs-warnings.js
  .github/actions/ci/start-server.js
  .github/workflows/ci.yml
Labels: Development

#4940 QOL Recipe to reset Refined Storage and Extra Storage crafter NBT
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/extrastorage/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/refinedstorage/shapeless.js
Labels: Enhancement

#4942 Implement Quezler's alternate idea
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/create/no_infinite_draining.js
Labels: Development
