Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-03, with the labels that each got.

#4309 [Expert] polished wood and eidolon progression fixes
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/ladder_planks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/planks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/minecraft/planks.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/eidolon/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/minecraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
Labels: Development

#4313 Blacklist respawnable mobs from melting for blood.
  config/bloodmagic-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/entity_melting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/eidolon/shaped.js
Labels: Enhancement

#4315 [Expert] bug fixes
  kubejs/data/eidolon/structures/lab.nbt
  kubejs/data/pneumaticcraft/structures/villages/mechanic_house_desert.nbt
  kubejs/data/pneumaticcraft/structures/villages/mechanic_house_plains.nbt
  kubejs/data/pneumaticcraft/structures/villages/mechanic_house_savanna.nbt
  kubejs/data/pneumaticcraft/structures/villages/mechanic_house_snowy.nbt
  kubejs/data/pneumaticcraft/structures/villages/mechanic_house_taiga.nbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/squeezer.js
  kubejs/server_scripts/enigmatica/kubejs/expert/loot_tables/block/disabled_blocks.js
Labels: Development

#4317 Tag Thief Hood as `armor/helm`
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/helms.js
Labels: Enhancement

#4318 Disable apothecary stand in eidolon structures
  kubejs/data/eidolon/structures/catacomb_lab.nbt
Labels: Development

#4320 Add Overworld worldgen bees to Beekeeper villager
  config/enigmatica/beekeeper.json
Labels: Enhancement

#4325 [Expert] Updates to Quest Book and other minor adjustments
  building_gadgets_patterns/pneumaticcraft/electrostatic_compressor.json
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  config/pneumaticcraft-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/compacting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/create/compacting.js
  schematics/PNC_electrostatic_compressor.nbt
Labels: Development

#4329 [Expert] Update Gates
  config/ftbquests/quests/chapters/gates_wip.snbt
Labels: Development

#4330 More work on gates
  config/ftbquests/quests/chapters/gates_wip.snbt
Labels: Development

#4334 [Expert] Add storage parts to advanced assembly table
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/advanced_assembly_table.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4338 Blacklist BM and Occultism from cardboard box. Expand restrictions to chalk and BM altar runes
  config/Mekanism/general.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/restrictions/restrictions.js
Labels: Development

#4336 Add new main menu panorama
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_0.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_1.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_2.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_3.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_4.png
  packmenu/resources/assets/minecraft/textures/gui/title/background/panorama_5.png
Labels: Enhancement

#4335 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/zh_cn.json
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
Labels: Enhancement

#4341 blacklist eidolon from cardboard box
  config/Mekanism/general.toml
Labels: Development

#4342 delete bak file...
  config/ars_nouveau/pickup-1.toml.bak
Labels: Development

#4343 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/zh_cn.json
Labels: Enhancement

#4359 Allow Tree Fertilizer to use any coral
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/shapeless.js
Labels: Enhancement

#4356 [Expert] Little logistics Integration
  defaultconfigs/littlelogistics-server.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/littlelogistics/shaped.js
Labels: Development

#4362 update restrictions translation strings
  kubejs/assets/kubejs/lang/en_us.json
Labels: Development

#4365 revert masticator change for drygmies
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/mob_spawner_blacklist.js
Labels: Development

#4370 [Expert] Increase the warning on the masticator quest
  config/ftbquests/quests/chapters/magic__adept.snbt
Labels: Development

#4371 1.0.0
  .gitignore
  automation/modpack-uploader.ps1
  automation/settings.ps1
  changelogs/CHANGELOG.md
  config/defaultoptions/keybindings.txt
  config/ftbquests/quests/chapters/magic__adept.snbt
  kubejs/startup_scripts/worldgen_remove.js
  minecraftinstance.json
Labels: Development

#4373 Expert server files
  .gitignore
  automation/modpack-uploader.ps1
  changelogs/CHANGELOG.md
  server_files_expert/server-guide.txt
  server_files_expert/server-setup-config.yaml
  server_files_expert/start-server.bat
  server_files_expert/start-server.sh
Labels: Development

#4375 [Expert] Revert restriction for occultism chalk
  kubejs/server_scripts/enigmatica/kubejs/expert/restrictions/restrictions.js
Labels: Development

#4378 Think of the Bees!
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/bee_larva.png
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/resourcefulbees/bees.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/constants/resourcefulbees.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#4384 [Expert] Tier 2 Magic dependency fixes
  config/ftbquests/quests/chapters/magic__adept.snbt
Labels: Enhancement

#4393 [Expert] Remove easy smeltery Pink Slime Ingots
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
Labels: Bug

#4405 Fix for Twig/Pinecone recipes eating shears
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/projectvibrantjourneys/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/projectvibrantjourneys/shapeless.js
Labels: Enhancement

#4426 [Expert] Allow automation to work with Occultism
  kubejs/server_scripts/enigmatica/kubejs/expert/restrictions/restrictions.js
Labels: Enhancement

#4363 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/nl_nl.json
  kubejs/assets/enigmatica/lang/nl_nl.json
  kubejs/assets/enigmatica/lang/ru_ru.json
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
  kubejs/assets/tconstruct/lang/zh_tw.json
  kubejs/assets/tetra/lang/zh_tw.json
  packmenu/resources/assets/enigmatica/lang/pt_br.json
Labels: Enhancement

#4435 [Expert] Sequenced Assembly Blocks -> Items, [Base] Remove Rail Melting Recipes
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/models/item/partial_alloybrick.json
  kubejs/assets/kubejs/models/item/partial_blastbrick.json
  kubejs/assets/kubejs/models/item/partial_cokebrick.json
  kubejs/assets/kubejs/textures/block/partial_alloybrick.png
  kubejs/assets/kubejs/textures/block/partial_blastbrick.png
  kubejs/assets/kubejs/textures/block/partial_cokebrick.png
  kubejs/assets/kubejs/textures/item/alloy_kiln_brick_model.png
  kubejs/assets/kubejs/textures/item/basalt_powder.png
  kubejs/assets/kubejs/textures/item/blast_brick.png
  kubejs/assets/kubejs/textures/item/blast_brick_blend.png
  kubejs/assets/kubejs/textures/item/blast_oven_brick_model.png
  kubejs/assets/kubejs/textures/item/coke_brick.png
  kubejs/assets/kubejs/textures/item/coke_brick_blend.png
  kubejs/assets/kubejs/textures/item/coke_oven_brick_model.png
  kubejs/assets/kubejs/textures/item/red_nether_brick.png
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/create/upright_on_belt.js
  kubejs/startup_scripts/block_registry.js
  kubejs/startup_scripts/item_registry.js
Labels: Maintenance

#4461 Add BYG and PVJ Cattails to dye recipes
  kubejs/server_scripts/enigmatica/kubejs/constants/dyes.js
Labels: Enhancement

#4462 [Expert] Fix Powah Reactor crafting to work with 'used' blocks
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
Labels: Enhancement

#4463 Quest fixes - allow any mechanical piston in Create, fix typo in Expert quests
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
Labels: Enhancement

#4464 [Expert] Change PNC assembly recipe to use computer craft computer
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
Labels: Enhancement

#4466 [Expert] Fix BM Part 2 Gate
  config/ftbquests/quests/chapters/gates_wip.snbt
Labels: Enhancement

#4460 [Expert] Disable Factory Placer because it doesn't respect Game Stages
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/mekansim/cardboard_blacklist.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
Labels: Enhancement

#4471 Disable Melting Golden Apples
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#4472 Add Eternal Steak/Beef to Seagull blacklist
  config/alexsmobs.toml
Labels: Enhancement

#4475 Implements blacklists for IE machines, as well as blocks with restrictions in Expert.
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/buildinggadgets/blacklists.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/blocks/buildinggadgets/blacklists.js
Labels: Enhancement

#4480 Fix typos in BG blacklist
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/buildinggadgets/blacklists.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/blocks/buildinggadgets/blacklists.js
Labels: Development

#4487 Disables flying structures and infested temple
  config/when-dungeons-arise-common.toml
Labels: Bug

#4482 [Expert] Remove Eidolon Magic Workbench
  building_gadgets_patterns/masterful_machinery/wicked_altar.json
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/gates_wip.snbt
  config/ftbquests/quests/chapters/hidden_quests.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  config/gamestages/known_stages.json
  config/jei/recipe-category-sort-order.ini
  config/masterful_machinery/controllers/wicked_altar.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/jei_hide_items.js
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/data/masterful_machinery/recipes/wicked_altar.json
  kubejs/server_scripts/enigmatica/kubejs/expert/loot_tables/block/disabled_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/block_transmutation.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/petal_apothecary.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/eidolon/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_lightning.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/wicked_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/materialis/modifiers.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/enriching.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/minecraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/restrictions/restrictions.js
  kubejs/startup_scripts/item_registry.js
  schematics/MM_wicked_altar.nbt
Labels: Enhancement

#4492 Remove Reinforced Stone from PNC Basic Tank
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
Labels: Maintenance

#4459 Disable Flies spawning outside of swamps
  config/alexsmobs/fly_spawns.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/interactio/item_fluid_transform.js
Labels: Enhancement

#4510 [Expert] Resolve soul enchanter gamestage mixup, preventing some players from placing after the update.
  config/ftbquests/quests/chapters/hidden_quests.snbt
Labels: Development

#4512 Add Little Logistics and Encyclopedia of Tinkering to Akashic Tome
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#4513 [Expert] Update Mechanical Crafter recipes to ignore NBT where appropriate.
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
Labels: Development

#4514 Make Blood available from trees again
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/fluid_extractor.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/tree_extractor.js
  kubejs/server_scripts/enigmatica/kubejs/constants/trees.js
Labels: Enhancement

#4515 Update Expert quests to accept Superheated Steel Blocks and Hot Compressed Iron Blocks as well as Ingots
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
Labels: Enhancement

#4516 [Expert] Add Quest for Deuterium Plant
  config/ftbquests/quests/chapters/tech_t3.snbt
Labels: Enhancement

#4517 Quest updates - Fix Iron Jetpack quest visibility
  config/ftbquests/quests/chapters/magic__adept.snbt
  config/ftbquests/quests/chapters/tools.snbt
Labels: Enhancement

#4518 Fix broken NBT on MLG-YOLO buckets from Loot
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/towers_of_the_wild/tower_chest.js
Labels: Enhancement

#4519 Catacombs Loot: Fix typos on some custom Caster Tomes, slightly reduce the rate of Blacker Lotuses
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/undergarden/catacombs.js
Labels: Enhancement

#4520 [Expert] Remove Terminite from Iron recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/immersiveengineering/arc_furnace.js
Labels: Enhancement

#4521 Fix typo in BM entity blacklist
  config/bloodmagic-common.toml
Labels: Development

#4524 [Expert] Fix uncraftable Assembly Controller
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
Labels: Enhancement

#4525 Convert stone slab recipes to use more types of stone
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/prettypipes/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/crafting_slabs.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/minecraft/shaped.js
Labels: Enhancement

#4527 Fix fluids given by Tinker's Quests to use proper fluids
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_epic.json
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_legendary.json
  kubejs/data/enigmatica/loot_tables/chests/quest_tinkers_rare.json
Labels: Bug

#4530 Explicitly state in the Expert quests how to obtain rock crystals. Remove superfluous Linking Tool from Astral Quests.
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
Labels: Enhancement

#4507 New Crowdin updates
  kubejs/assets/kubejs/lang/zh_cn.json
Labels: Enhancement
