Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-01, with the labels that each got.

#3975 Remove Enderium Spawn Egg Mutation
  config/resourcefulbees/bees/gem/Diamond.json
Labels: Maintenance

#3976 Disable Mimicream Dupining
  config/alexsmobs.toml
Labels: Enhancement

#3977 Add Sentient Harm quest to Blood Magic
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
Labels: Enhancement

#3973 [Expert] Assorted Fixes
  config/Mekanism/client.toml
  config/ftbquests/quests/chapters/gates_wip.snbt
  config/ftbquests/quests/chapters/magic__master.snbt
  config/ftbquests/quests/chapters/tinkers_construct.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/block/partial_alloybrick.png
  kubejs/assets/kubejs/textures/block/partial_blastbrick.png
  kubejs/assets/kubejs/textures/block/partial_cokebrick.png
  kubejs/assets/kubejs/textures/item/incomplete_book.png
  kubejs/assets/kubejs/textures/item/incomplete_capacitor_basic_large.png
  kubejs/assets/kubejs/textures/item/ritual_dummy.png
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/generator_fuel.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/nucleosynthesizing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/powah/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/fluids/forge/fluids.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/sophisticatedbackpacks/backpacks.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_0_luminous.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_1_starlight.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_2_celestial.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/enriching.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/nucleosynthesizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/storagedrawers/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/powah/shaped.js
  kubejs/startup_scripts/block_registry.js
  kubejs/startup_scripts/item_registry.js
  kubejs/startup_scripts/multiblock_gamestages.js
Labels: Development

#3981 [expert] more weaknbt fixes...
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/soulforge.js
Labels: Development

#3979 Rf tools and mek config updates
  config/Mekanism/gear.toml
  config/Mekanism/general.toml
  config/Mekanism/machine-storage.toml
  config/Mekanism/machine-usage.toml
  config/Mekanism/tiers.toml
  config/Mekanism/tools-client.toml
  config/Mekanism/tools.toml
  config/configswapper/expert/config/Mekanism/machine-storage.toml
  config/configswapper/expert/serverconfig/rftoolspower-server.toml
  config/configswapper/normal/config/Mekanism/machine-storage.toml
  config/configswapper/normal/serverconfig/rftoolspower-server.toml
Labels: Development

#3986 [Expert] Minor Recipe Adjustments
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/sophisticatedbackpacks/shaped.js
  kubejs/startup_scripts/multiblock_gamestages.js
Labels: Development

#3989 Separate Rock Path, Stone Bricks, and Polished Andesite crafting recipes
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/cfm/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/shaped.js
Labels: Enhancement

#3990 Add Crushing recipes for petcoke dust. Add Thermal Steel recipe using petcoke dust.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/bloodmagic/arc.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/milling.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_crushing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
Labels: Enhancement

#3991 Enable Chiselling between glass types
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/glass.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/glass_panes.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
  kubejs/server_scripts/enigmatica/kubejs/functions.js
Labels: Enhancement

#3996 [Expert] Fix T2 Apiary Recipe
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Maintenance

#3998 [Expert] weak NBT fix
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
Labels: Development

#3999 Resolve recipe conflict with knives and chisels
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/chisel/shaped.js
Labels: Enhancement

#4000 Birthing altar updates
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/animal_spawner.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/naturesaura/animal_spawner.js
Labels: Enhancement

#4001 [Expert] Fix Mining Reagent
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
Labels: Development

#4003 Update tech_t2.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
Labels: Development

#4006 add missing slabfish from #4000
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
Labels: Development

#4007 Create Altar of Birthing recipes for ducks and deer
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
Labels: Enhancement

#4019 Remove psimetal exosuit from materialis
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#4020 Prevent IE Ores from generating on first launch.
  defaultconfigs/immersiveengineering-server.toml
Labels: Bug

#4009 [Expert] More Recipe Overhauls
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/glass.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_dyes.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/blast_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/travel_anchors/shaped.js
Labels: Development

#4021 [Expert] reduce cost of botania platforms
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
Labels: Development

#4034 Bee Fixes
  config/resourcefulbees/bees/dev/Kitten.json
  config/resourcefulbees/bees/dev/Oreo.json
  config/resourcefulbees/bees/dev/Starry_Lexxie.json
  config/resourcefulbees/bees/dev/Yeti.json
  config/resourcefulbees/common.toml
  config/resourcefulbees/honey/Starry.json
  config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Maintenance

#4035 [Expert] Automated Iridescent Altar
  building_gadgets_patterns/masterful_machinery/auto_iridescent_altar.json
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  config/masterful_machinery/controllers/auto_iridescent_altar.json
  kubejs/assets/kubejs/textures/block/storage_steel.png
  kubejs/data/masterful_machinery/recipes/auto_iridescent_altar.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_3_iridescent.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/auto_iridescent_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
Labels: Development

#4049 Reduce output of chains when melting in tinkers
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
Labels: Enhancement

#4050 Update RS Crafter quest to add information about distributed crafting
  config/ftbquests/quests/chapters/refined_storage.snbt
Labels: Enhancement

#4046 [Expert] Masterful Machines - Advanced Assembly Table
  .gitignore
  building_gadgets_patterns/masterful_machinery/advanced_assembly_table.json
  building_gadgets_patterns/masterful_machinery/auto_iridescent_altar.json
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  config/masterful_machinery/controllers/advanced_assembly_table.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/block/radiator.png
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/data/masterful_machinery/recipes/advanced_assembly_table.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/advanced_assembly_table.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4051 [Expert] QoL Tweaks
  config/configswapper/expert/config/Mekanism/machine-storage.toml
  config/configswapper/expert/config/Mekanism/machine-usage.toml
  config/configswapper/expert/config/industrialforegoing/machine-core.toml
  config/ftbquests/quests/chapters/gates_wip.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/thermal/textures/item/syrup_bottle.png
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/undergarden_saplings.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/crucible.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/pulverizer.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_1_starlight.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_3_iridescent.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/alchemytable.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/emptying.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/filling.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/casting_basin.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/casting_table.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/bottler.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/press.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4057 Ancient Wood sawing and rod improvements
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/rods.js
Labels: Enhancement

#4058 Add Sawing recipes for Ancient Wood and Bark
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/sawmill.js
Labels: Enhancement

#4056 Some Atum QOL suggestions
  config/ftbquests/quests/chapters/adventure.snbt
  defaultconfigs/scannable-server.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/compote/composting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/blasting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/smelting.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/forge/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/atum/linen.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ores.js
Labels: Enhancement

#4065 Update Astral Quest descriptions for clarity
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
Labels: Enhancement

#4067 Fix issues with crafting items using thermal cells
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersivepetroleum/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/portality/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/powah/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
Labels: Development

#4068 manually add glass to stonecutter tag
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/stonecutter.js
Labels: Development

#4074 Reduce Sooty Spawn Weight
  config/resourcefulbees/bees/natural/Coal.json
Labels: Maintenance

#4075 [Expert] Machine Speed and Ore Processing tweaks
  config/configswapper/expert/config/Mekanism/generators.toml
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  config/configswapper/normal/config/Mekanism/generators.toml
  config/configswapper/normal/serverconfig/immersiveengineering-server.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/unification/unify_materials.js
Labels: Development

#4061 [Expert] Fixes for MM Iridescent Altar and prep for future machines
  building_gadgets_patterns/masterful_machinery/advanced_assembly_table.json
  building_gadgets_patterns/masterful_machinery/auto_iridescent_altar.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/astrogro.png
  kubejs/assets/kubejs/textures/item/astrogro.png.mcmeta
  kubejs/data/masterful_machinery/recipes/auto_iridescent_altar.json
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/dankstorage/blacklisted_usage.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mininggadgets/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/bottler.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4077 [Expert] Buff power output of Modular Routers
  config/configswapper/expert/config/modularrouters-common.toml
  config/configswapper/normal/config/modularrouters-common.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
Labels: Development

#4080 [Expert] Revert IE Crusher speed upgrade
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
Labels: Development

#4081 Hide visible Expert quests for Normal mode.
  config/ftbquests/quests/chapters/magic__adept.snbt
  config/ftbquests/quests/chapters/magic__master.snbt
  config/ftbquests/quests/chapters/tech_t3.snbt
Labels: Bug

#4083 [Expert] Modular Routers recipe pass and general cleanup
  config/ars_nouveau/chaining.toml
  config/ars_nouveau/filter_block.toml
  config/ars_nouveau/filter_entity.toml
  config/ars_nouveau/filter_item.toml
  config/ars_nouveau/filter_living.toml
  config/ars_nouveau/filter_living_not_monster.toml
  config/ars_nouveau/filter_living_not_player.toml
  config/ars_nouveau/filter_monster.toml
  config/ars_nouveau/filter_player.toml
  config/ars_nouveau/lay_on_hands.toml
  config/ars_nouveau/ray.toml
  config/ars_nouveau/reverse_direction.toml
  defaultconfigs/tconplanner-client.toml
  kubejs/client_scripts/item_modifiers/jei_add_items.js
  kubejs/client_scripts/item_modifiers/jei_add_subtypes.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/atum/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/betterend/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/environmental/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/casting_basin.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/farmersdelight/farmersdelight.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/armor/shields.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/modularrouters/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/modularrouters/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4079 Make nbt extracters not require the programmer
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
Labels: Development

#4090 Disable IE Mineral nodes in the End as they're incompatible with the dimension.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/minerals.js
Labels: Enhancement

#4091 Add missing Lang entry for Sentient Harm
  kubejs/assets/enigmatica/lang/en_us.json
Labels: Enhancement

#4094 [Expert] General Adjustments and Occultism Miner tweaks
  config/configswapper/expert/serverconfig/occultism-server.toml
  config/configswapper/normal/serverconfig/occultism-server.toml
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/magic_lamp.png
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/item/fishing_treasure.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/amadron_survey_loot_tables.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/soggy_treasure_box.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/basic_resources.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/fish.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_basic_resources.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/redstonepen/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/occultism/miners.js
  kubejs/server_scripts/enigmatica/kubejs/constants/fish.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/blast_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4097 [Expert] Stellar Neutron Activator MM
  building_gadgets_patterns/masterful_machinery/stellar_neutron_activator.json
  config/masterful_machinery/controllers/advanced_assembly_table.json
  config/masterful_machinery/controllers/auto_iridescent_altar.json
  config/masterful_machinery/controllers/stellar_neutron_activator.json
  kubejs/assets/kubejs/textures/block/radiator.png
  kubejs/assets/kubejs/textures/block/storage_steel.png
  kubejs/client_scripts/item_modifiers/jei_add_subtypes.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/data/masterful_machinery/recipes/stellar_neutron_activator.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/stellar_neutron_activator.js
Labels: Development

#4107 Remove duplicate construction paste recipe.
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#4108 Allow Quark turf to be made from more types of grass
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/quark/shaped.js
Labels: Enhancement

#4110 remove attempts at using tags for glass stonecutting. Make a big list.
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Development

#4111 [Expert] fix lapis compound
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
Labels: Development

#4113 0.5.25
  automation/settings.ps1
  building_gadgets_patterns/masterful_machinery/stellar_neutron_activator.json
  config/Advancedperipherals/metaphysics.toml
  config/Advancedperipherals/peripherals.toml
  config/configswapper/expert/serverconfig/occultism-server.toml
  config/configswapper/normal/serverconfig/occultism-server.toml
  config/jei/recipe-category-sort-order.ini
  config/masterful_machinery/controllers/advanced_assembly_table.json
  config/masterful_machinery/controllers/auto_iridescent_altar.json
  config/masterful_machinery/controllers/stellar_neutron_activator.json
  kubejs/assets/enigmatica/lang/en_us.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/block/radiator.png
  kubejs/assets/kubejs/textures/block/storage_steel.png
  kubejs/assets/kubejs/textures/item/magic_lamp.png
  kubejs/client_scripts/item_modifiers/jei_add_subtypes.js
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/data/masterful_machinery/recipes/stellar_neutron_activator.json
  kubejs/server_scripts/enigmatica/kubejs/base/item/fishing_treasure.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/amadron_survey_loot_tables.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/soggy_treasure_box.js
  kubejs/server_scripts/enigmatica/kubejs/base/player/logged_in.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/minerals.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/basic_resources.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/fish.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/dimensional_mineshaft/ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_basic_resources.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/occultism/miner_ores.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/prettypipes/shapeless.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/quark/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/redstonepen/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/ladder_planks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/occultism/miners.js
  kubejs/server_scripts/enigmatica/kubejs/constants/fish.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/blast_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/stellar_neutron_activator.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/packmode.js
  kubejs/startup_scripts/item_registry.js
  minecraftinstance.json
Labels: Development

#4116 Add more BYG mushrooms to the market
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/byg_saplings.json
Labels: Enhancement

#4118 Fix input for Fried Potato Cubes
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
Labels: Enhancement

#4119 remove lingering one probe recipe for PNC helmet
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
Labels: Enhancement

#4129 [Expert] remove unintended alloy recipe for stack upgrade
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/alloy.js
Labels: Development

#4135 [Expert] Added weakNBT tag to Scythe and Cap to fix mycelial generator recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#4136 [Expert] Shuffle a few machines around on the Machinery Schematics
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/startup_scripts/multiblock_gamestages.js
Labels: Development

#4137 Minor tweaks
  config/alexsmobs/emu_spawns.json
  config/alexsmobs/gazelle_spawns.json
  config/alexsmobs/guster_spawns.json
  config/alexsmobs/kangaroo_spawns.json
  config/alexsmobs/komodo_dragon_spawns.json
  config/alexsmobs/rattlesnake_spawns.json
  kubejs/client_scripts/item_modifiers/jei_descriptions.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/astralsorcery/shrine_chest.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/atum/chests/pyramid_chest.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/naturesaura/animal_spawner.js
Labels: Development

#4084 Fluid Storage and Automation quests
  config/ftbquests/quests/chapters/automation.snbt
  config/ftbquests/quests/chapters/modular_routers.snbt
  config/ftbquests/quests/chapters/storage.snbt
Labels: Enhancement

#4149 Storage quests update
  config/ftbquests/quests/chapters/automation.snbt
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/integrated_dynamics.snbt
  config/ftbquests/quests/chapters/refined_storage.snbt
  config/ftbquests/quests/chapters/storage.snbt
  config/ftbquests/quests/chapters/tinkers_construct.snbt
  config/ftbquests/quests/chapters/tools.snbt
Labels: Enhancement

#4150 Add marshmallow and chicory roots to Market
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/simplefarming_seeds.json
Labels: Enhancement

#4154 Apotheosis boss file formatting
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/apotheosis/bosses.js
Labels: Development

#4156 Disables Requesting Halo animation
  config/interactive_corporea-client.toml
Labels: Development

#4142 [Expert] Endgame Recipe Prep
  building_gadgets_patterns/masterful_machinery/gaia_reactor.json
  config/masterful_machinery/controllers/gaia_reactor.json
  config/quark-common.toml
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/data/masterful_machinery/recipes/gaia_reactor.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_3_iridescent.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/alloy.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/auto_iridescent_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/gaia_reactor.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mininggadgets/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/startup_scripts/item_registry.js
Labels: Development
