Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-04, with the labels that each got.

#4546 [Expert] Attempt to clarify Gamestage message for IE Multiblocks.
  kubejs/startup_scripts/multiblock_gamestages.js
Labels: Enhancement

#4547 Update Astral Quests to clarify how to make the luminous crafting table.
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
Labels: Enhancement

#4548 [Expert] Add note about seals in tech quests for Arboreal Extractor
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
Labels: Enhancement

#4549 [Expert] Reduce cost of PNCs Thermal Lagging
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
Labels: Enhancement

#4551 Correct the Enchanting Apparatus quest to have the right sized area.
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Enhancement

#4562 [Expert] Fix for incompletable IE quests
  config/ftbquests/quests/chapters/industrial_foregoing.snbt
Labels: Enhancement

#4563 [Expert] Fix for uncraftable Wicked Weave
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/eidolon/shaped.js
Labels: Enhancement

#4561 Disable Mob Fleeing for Small Ships
  config/smallships-common.toml
Labels: Enhancement

#4572 Allow dying 8 rockwool with 1 dye
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
Labels: Enhancement

#4576 Update Integrated Dynamics quest to be doable in Expert
  config/ftbquests/quests/chapters/integrated_dynamics.snbt
Labels: Enhancement

#4577 Allow sawing Livingwood to 6 planks and batch dying Ceramics
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/create/splashing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/cutting.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/mekanism/sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pedestals/pedestal_sawing.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/sawmill.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/enigmatica/washables.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/ceramics.js
Labels: Enhancement

#4575 Allow more items to stack to 64
  kubejs/startup_scripts/better_stacks.js
Labels: Enhancement

#4582 [Expert] reduce unintentionally high stoneling aura cost
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/animal_spawner.js
Labels: Enhancement

#4584 Add villager seats mention in tips
  kubejs/assets/enigmatica/tips/villager_seats.json
Labels: Enhancement

#4593 [Expert] Add clarification to Gates quests concerning 'normal' quest progression.
  config/ftbquests/quests/chapters/gates_wip.snbt
Labels: Enhancement

#4594 Remove Sentient Pick reward from BM
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
Labels: Enhancement

#4595 Adjust quest description for Pressure Chamber
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
Labels: Enhancement

#4596 [Expert] Revert Tinker's Traveller's Gear to use Copper
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tconstruct/shaped.js
Labels: Enhancement

#4597 Correct output for Utherium ore in Smeltery
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
Labels: Enhancement

#4612 [Expert] Correct Thermal saw blade to use tinker's large plate instead of materialis.
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/press.js
Labels: Enhancement

#4613 Fixes typo in Building quests
  config/ftbquests/quests/chapters/building.snbt
Labels: Enhancement

#4614 Update Hepatizon recipes to match new Tinker's output
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/induction_smelter.js
Labels: Enhancement

#4615 Make Scintling Goo and empty buckets stack to 64
  kubejs/startup_scripts/better_stacks.js
Labels: Enhancement

#4616 minor shift in quest icon placement
  config/ftbquests/quests/chapters/magic__adept.snbt
Labels: Development

#4622 Restore missing large excavator mineral nodes
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  config/configswapper/normal/serverconfig/immersiveengineering-server.toml
  defaultconfigs/immersiveengineering-server.toml
Labels: Enhancement

#4625 [Expert] Recipe tweaks
  building_gadgets_patterns/immersive_engineering/automated_engineers_workbench.txt
  building_gadgets_patterns/masterful_machinery/enigmatic_tree_of_life.json
  config/ftbquests/quests/chapters/building.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  kubejs/data/masterful_machinery/recipes/enigmatic_tree_of_life.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_3_iridescent.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/integratedcrafting/shaped.js
  kubejs/startup_scripts/better_stacks.js
  schematics/MM_enigmatic_tree_of_life.nbt
Labels: Enhancement

#4643 Fix quest referencing Magic Workbench instead of Godforged Block
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
Labels: Enhancement

#4646 Bricks are no longer throwable
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/supplementaries/throwable_bricks.js
Labels: Enhancement

#4647 Adds centrifuge recipe for Slimy Wart to get some ichor and blood from them when farming Tinker's Trees
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/centrifuge.js
Labels: Enhancement

#4649 [Expert] Update Ender Chest recipe
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/enderstorage/shaped.js
Labels: Enhancement

#4644 [Expert] Remove dependency on IE coke oven
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/immersiveengineering/blast_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/machine/pyrolyzer.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/replace_input.js
Labels: Enhancement

#4659 [Expert] Buff Mek Energy Cubes compared to Powah cells
  config/configswapper/expert/config/Mekanism/tiers.toml
  config/configswapper/normal/config/Mekanism/tiers.toml
Labels: Enhancement

#4666 [Expert] Quest clarifications for Lightning Crafting and a warning to diversify when approaching tech/magic
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/gates_wip.snbt
Labels: Enhancement

#4668 Remove Starlight as secondary when melting Starmetal in Foundary
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/melting.js
Labels: Bug

#4673 Fix tooltip typos on med/heavy machinery schematics
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
Labels: Enhancement

#4675 [Expert] Reduce power cost of Sludge Refiner and Resourceful Furnace
  config/configswapper/expert/config/industrialforegoing/machine-resource-production.toml
Labels: Enhancement

#4685 [Expert] Quest updates
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/eidolon_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_1_wip.snbt
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
Labels: Enhancement

#4687 [Expert] RAM Chip Improvements
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/advanced_ram_chip.png
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/kubejs/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#4689 Bee Maintainence
  config/resourcefulbees/bees/alloy/Brass.json
  config/resourcefulbees/bees/alloy/Bronze.json
  config/resourcefulbees/bees/alloy/Constantan.json
  config/resourcefulbees/bees/alloy/Electrum.json
  config/resourcefulbees/bees/alloy/Enderium.json
  config/resourcefulbees/bees/alloy/Invar.json
  config/resourcefulbees/bees/alloy/Lumium.json
  config/resourcefulbees/bees/alloy/Signalum.json
  config/resourcefulbees/bees/alloy/Steel.json
  config/resourcefulbees/bees/tech/PCBee.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/centrifuge.js
Labels: Maintenance

#4696 Make "effect powders" node depend on "ebb and flow" instead
  config/ftbquests/quests/chapters/natures_aura.snbt
Labels: Enhancement

#4693 Simplify atum quest triggers
  config/ftbquests/quests/chapters/adventure.snbt
Labels: Enhancement

#4698 Update Apotheosis configs to new JSON format
  config/apotheosis/enchantments.cfg
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/apotheosis/boon_drops.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/apotheosis/spawner_modifier.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipetypes/apotheosis/spawner_modifier.js
Labels: Enhancement

#4702 Amadron Improvements
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  kubejs/client_scripts/item_modifiers/tooltips.js
Labels: Enhancement

#4703 [Expert] Update Mythic Botany Runes to assist with automation
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
Labels: Enhancement

#4707 Update Advanced Assembly Table Schematics to remove excess blocks
  building_gadgets_patterns/masterful_machinery/advanced_assembly_table.json
  config/ftbquests/quests/chapters/powah.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  schematics/MM_advanced_assembly_table.nbt
Labels: Enhancement

#4720 [Expert] Alternate recipes for Etching Acid and Venom
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/monster_mash.png
  kubejs/client_scripts/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mixing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#4721 [Expert] Introduce some late game alternative recipes for Mechancial Crafts
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/portality/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/refinedstorage/shaped.js
  kubejs/startup_scripts/item_registry.js
Labels: Enhancement

#4724 Material Improvements
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/unification/unify_materials.js
Labels: Enhancement

#4730 [Expert] Update BM quests to accept any bloodstone.
  config/ftbquests/quests/chapters/magic__master.snbt
Labels: Enhancement

#4731 [Expert] Add Chalice and Shifting Star to Automated Iridescent Altar
  config/bloodmagic-common.toml
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/entity_melting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/auto_iridescent_altar.js
Labels: Enhancement
