Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-06, with the labels that each got.

#4957 Fix Mining Gadget Quests so the recipe can be clicked to from the quest.
  config/ftbquests/quests/chapters/tools.snbt
Labels: Enhancement

#4958 [Expert] Quest clarifications
  config/ftbquests/quests/chapters/adventure.snbt
  config/ftbquests/quests/chapters/magic__adept.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/atum/artifacts.js
Labels: Enhancement

#4959 Add more tags to atum items.
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/atum/godforged_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/atum/godshards.js
Labels: Development

#4960 Allow Pink Wither drilling in any biome
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/industrialforegoing/laser_drill_fluid.js
Labels: Enhancement

#4969 [Expert] Fix unclear quest progression in circuit quests. Hide Bragging Rights in Normal.
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
  config/ftbquests/quests/chapters/tech_t3.snbt
Labels: Enhancement

#4900 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/zh_cn.json
  config/resourcefulbees/resources/assets/resourcefulbees/lang/zh_tw.json
  kubejs/assets/enigmatica/lang/ko_kr.json
  kubejs/assets/enigmatica/lang/zh_cn.json
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
  kubejs/assets/ponderjs/lang/ko_kr.json
  kubejs/assets/ponderjs/lang/zh_cn.json
  kubejs/assets/ponderjs/lang/zh_tw.json
  kubejs/assets/tconstruct/lang/ko_kr.json
  kubejs/assets/tetra/lang/ko_kr.json
Labels: Enhancement

#4695 Mention that steady growth powder can prevent flower spam
  config/ftbquests/quests/chapters/natures_aura.snbt
Labels: Enhancement

#4971 Fix Building Gadgets Blacklists
  kubejs/server_scripts/enigmatica/kubejs/base/tags/blocks/buildinggadgets/blacklists.js
  kubejs/server_scripts/enigmatica/kubejs/expert/restrictions/restrictions.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/blocks/buildinggadgets/blacklists.js
Labels: Enhancement

#4972 Add fishing rod search tags
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/tools/fishing_rods.js
Labels: Enhancement

#4973 `tag` pneumaticcraft:pressurable
  .github/actions/ci/node/.gitignore
  .github/actions/ci/node/compare_artifact-tags.js
  .github/actions/ci/node/compare_download-artifact.js
  .github/actions/ci/node/package-lock.json
  .github/actions/ci/node/package.json
  .github/workflows/ci.yml
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/air.js
Labels: Enhancement

#4986 [Expert] Re-enable Docks for Dank/Tank Nulls
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/dankstorage/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/tanknull/shaped.js
Labels: Enhancement

#4993 `ci` detect global constants and functions
  .github/actions/ci/README.md
  .github/actions/ci/kubejs/kubejs-post.js
  .github/actions/ci/kubejs/kubejs-pre.js
  .github/actions/ci/node/kubejs-list-added-globals.js
  .github/actions/ci/node/package-lock.json
  .github/actions/ci/node/package.json
  .github/workflows/ci.yml
Labels: Development

#5003 Add missing loot table for Eidolon's polished wood pillar
  kubejs/data/eidolon/loot_tables/blocks/polished_wood_pillar.json
Labels: Enhancement

#5004 [Expert] Update layout in Magic Mastery Chapter for clarity
  config/ftbquests/quests/chapters/magic__master.snbt
Labels: Enhancement

#5005 [Expert] Reduce mana/blood cost of dislocation runes
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
Labels: Enhancement

#4996 Remove the catnip larva in favor of the kitten larva (#4937)
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/resourcefulbees/shapeless.js
Labels: Maintenance

#4970 New Crowdin updates
  kubejs/assets/enigmatica/lang/af_za.json
  kubejs/assets/enigmatica/lang/ar_sa.json
  kubejs/assets/enigmatica/lang/cs_cz.json
  kubejs/assets/enigmatica/lang/da_dk.json
  kubejs/assets/enigmatica/lang/de_de.json
  kubejs/assets/enigmatica/lang/es_es.json
  kubejs/assets/enigmatica/lang/fr_fr.json
  kubejs/assets/enigmatica/lang/it_it.json
  kubejs/assets/enigmatica/lang/ja_jp.json
  kubejs/assets/enigmatica/lang/ko_kr.json
  kubejs/assets/enigmatica/lang/nl_nl.json
  kubejs/assets/enigmatica/lang/no_no.json
  kubejs/assets/enigmatica/lang/pt_br.json
  kubejs/assets/enigmatica/lang/ru_ru.json
  kubejs/assets/enigmatica/lang/sv_se.json
  kubejs/assets/enigmatica/lang/tr_tr.json
  kubejs/assets/enigmatica/lang/zh_cn.json
  kubejs/assets/enigmatica/lang/zh_tw.json
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
Labels: Enhancement

#5010 quest text clarification
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
Labels: Maintenance

#5021 [Expert] Reduces the cost of making each Dimensional Mastery Shard
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
Labels: Enhancement

#5025 Remove glass panes from the glass tag
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/glass.js
Labels: Enhancement

#5026 more glass tag fixes
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
Labels: Enhancement

#5027 Add Advanced Peripherals book to Akashic Tome
  config/ftbquests/quests/chapters/getting_started.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/shapeless.js
Labels: Enhancement

#5030 Trim enchants available in Astral's Resplendent Prism
  config/configswapper/expert/serverconfig/astralsorcery.toml
  config/configswapper/normal/serverconfig/astralsorcery.toml
  defaultconfigs/astralsorcery.toml
Labels: Enhancement

#5031 Allow PNC elevators to render properly
  defaultconfigs/entity_culling-client.toml
Labels: Enhancement
