Repository EnigmaticaModpacks/Enigmatica6, pull requests merged in 2022-02, with the labels that each got.

#4165 [Expert] RFTools Machine Frame Models/Textures
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/models/block/coated_machine_frame_top.json
  kubejs/assets/kubejs/models/block/rough_machine_frame.json
  kubejs/assets/kubejs/models/block/rough_machine_frame_top.json
  kubejs/assets/kubejs/textures/block/coated_machine_frame_top.png
  kubejs/assets/kubejs/textures/block/rough_machine_frame.png
  kubejs/assets/kubejs/textures/block/rough_machine_frame_top.png
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/compacting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
  kubejs/startup_scripts/block_registry.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4169 [Expert] Reduce cost of Volume Upgrades
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
Labels: Development

#4170 [Expert] Change final step to use the blood altar instead of runic altar
  kubejs/server_scripts/enigmatica/kubejs/expert/unification/unify_materials.js
Labels: Development

#4171 [Expert] QoL changes for Compacting upgrades, cleanup on filters used in crafting
  config/guardvillagers-client.toml
  config/guardvillagers-common.toml
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/sophisticatedbackpacks/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/thermal/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/unification/unify_materials.js
Labels: Development

#4172 [Expert] QoL changes for Compacting upgrades, cleanup on filters used in crafting
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4160 [Expert] Bragging Rights
  building_gadgets_patterns/masterful_machinery/enigmatic_tree_of_life.json
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
  config/masterful_machinery/controllers/enigmatic_tree_of_life.json
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/client_scripts/expert/item_modifiers/jei_hide_items.js
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/data/masterful_machinery/recipes/enigmatic_tree_of_life.json
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/mininggadgets/mininggadgets.js
  kubejs/server_scripts/enigmatica/kubejs/expert/loot_tables/block/disabled_blocks.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/arc.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/nucleosynthesizing.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/rune_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/items/mythicbotany/ritual_runes.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4183 [Expert] Fix RFTools Storage Module Progression
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped_coby_nbt.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/rftools/shaped_copy_nbt.js
Labels: Development

#4187 Gear press uses IE gear form
  kubejs/server_scripts/enigmatica/kubejs/normal/unification/unify_materials.js
Labels: Enhancement

#4193 [Expert] Interactive Corporea integration
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Development

#4199 [Expert] Fix issue with luminizers
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Development

#4209 fix powah player transmitter title
  config/ftbquests/quests/chapters/powah.snbt
Labels: Enhancement

#4210 Increase output rate of Powah Thermo Generators
  config/configswapper/expert/config/powah/energy/generators/thermo_gen.toml
  config/configswapper/normal/config/powah/energy/generators/thermo_gen.toml
Labels: Enhancement

#4201 [Expert] Adjusting end game requirements
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/undergarden/catacombs.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mekanism/mek_data.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/tree_ritual.js
Labels: Development

#4215 [Expert] Bring Dandelifeon earlier
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/petal_apothecary.js
Labels: Development

#4147 New Crowdin updates
  config/resourcefulbees/resources/assets/resourcefulbees/lang/es_es.json
  config/resourcefulbees/resources/assets/resourcefulbees/lang/sv_se.json
  kubejs/assets/enigmatica/lang/es_es.json
  kubejs/assets/enigmatica/lang/sv_se.json
  kubejs/assets/kubejs/lang/af_za.json
  kubejs/assets/kubejs/lang/ar_sa.json
  kubejs/assets/kubejs/lang/cs_cz.json
  kubejs/assets/kubejs/lang/da_dk.json
  kubejs/assets/kubejs/lang/de_de.json
  kubejs/assets/kubejs/lang/es_es.json
  kubejs/assets/kubejs/lang/fr_fr.json
  kubejs/assets/kubejs/lang/it_it.json
  kubejs/assets/kubejs/lang/ja_jp.json
  kubejs/assets/kubejs/lang/ko_kr.json
  kubejs/assets/kubejs/lang/nl_nl.json
  kubejs/assets/kubejs/lang/no_no.json
  kubejs/assets/kubejs/lang/pt_br.json
  kubejs/assets/kubejs/lang/ru_ru.json
  kubejs/assets/kubejs/lang/sv_se.json
  kubejs/assets/kubejs/lang/tr_tr.json
  kubejs/assets/kubejs/lang/zh_cn.json
  kubejs/assets/kubejs/lang/zh_tw.json
  kubejs/assets/ponderjs/lang/es_es.json
  kubejs/assets/tetra/lang/es_es.json
Labels: Enhancement

#4216 [Expert] Quest updates to mention the custom Masterful Machines in the pack
  config/ftbquests/quests/chapters/magic__master.snbt
  config/ftbquests/quests/chapters/tech_t3.snbt
Labels: Development

#4184 Industrial Deuterium Plant
  building_gadgets_patterns/masterful_machinery/industrial_deuterium_plant.json
  config/masterful_machinery/controllers/industrial_deuterium_plant.json
  kubejs/client_scripts/expert/item_modifiers/jei_descriptions.js
  kubejs/data/masterful_machinery/recipes/industrial_deuterium_plant.json
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/mechanical_crafting.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/industrial_deuterium_plant.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/shaped.js
Labels: Development

#4217 [Expert] Add missing lamp to irradiated miner
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
Labels: Development

#4224 [Expert] Nebu and corundum tweaks
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  config/ftbquests/quests/chapters/tech_t2.snbt
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/botania/runic_altar.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_explode.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/thermo_plant.js
Labels: Development

#4233 Remove unused molten metals from Botania added by KubeJS. Materialis has them already.
  kubejs/startup_scripts/fluid_registry.js
Labels: Enhancement

#4234 Add Upgrade Aquatic kelp as uncommon loot in Neptune's Bounty
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/aquaculture/aquaculture_boxes.js
Labels: Enhancement

#4235 Re-add missing trapped chest recipe
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/shapeless.js
Labels: Bug

#4243 [Expert] Fix for invar dust
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/interactio/item_explode.js
Labels: Development

#4236 [Expert] Update Birthing Altar Recipes
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/animal_spawner.js
Labels: Development

#4244 [Expert] PNC updates
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/sequenced_assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/shaped.js
Labels: Development

#4245 Remove reference to exact output for Marid Crusher
  config/ftbquests/quests/chapters/occultism.snbt
Labels: Development

#4256 Add End Mineral Survey as replacement to previously disabled IE mineral nodes.
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/enigmatica/amadron_survey_loot_tables.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/pneumaticcraft/amadron.js
Labels: Enhancement

#4263 [Expert] Fixes surrounding early Ars Nouveau and Eidolon
  config/ftbquests/quests/chapters/expert__tier_2_wip.snbt
  config/ftbquests/quests/chapters/gates_wip.snbt
  config/ftbquests/quests/chapters/magic__adept.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/alexsmobs/seal_reward.js
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/projectvibrantjourneys/block.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/replace_input.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/eidolon/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/farmersdelight/cooking_pot.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/naturesaura/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/normal/recipes/replace_input.js
Labels: Development

#4266 Fix typo in storage quests: "$storage/bag"
  config/ftbquests/quests/chapters/storage.snbt
  kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage/bags.js
Labels: Enhancement

#4268 Ars Nouveau Quest update to help make Expert/Normal work together
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Enhancement

#4269 [Expert] Fix seal rewards
  kubejs/data/alexsmobs/loot_tables/gameplay/seal_reward.json
  kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/alexsmobs/seal_reward.js
Labels: Development

#4275 [Expert] Tree of Life update - Build graciously provided by Howester84
  building_gadgets_patterns/masterful_machinery/enigmatic_tree_of_life.json
  config/masterful_machinery/controllers/enigmatic_tree_of_life.json
  kubejs/data/masterful_machinery/recipes/enigmatic_tree_of_life.json
Labels: Development

#4277 Mm machine schematics
  schematics/MM_advanced_assembly_table.nbt
  schematics/MM_auto_iridescent_altar.nbt
  schematics/MM_enigmatic_tree_of_life.nbt
  schematics/MM_gaia_reactor.nbt
  schematics/MM_industrial_deuterium_plant.nbt
  schematics/MM_stellar_neutron_activator.nbt
Labels: Development

#4278 Blacklist Ars Familiars and Target Dummies from Sacrifices
  config/bloodmagic-common.toml
Labels: Enhancement

#4280 Swap to tconstruct's native fluids for Refined Glowstone and Refined Obsidian
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/thermal/machine/chiller.js
Labels: Enhancement

#4283 [Expert] Progression fixes and more
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants.js
  kubejs/client_scripts/expert/item_modifiers/tooltips.js
  kubejs/server_scripts/enigmatica/kubejs/base/tags/entity/enigmatica/elementals.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/bloodmagic/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/occultism/ritual.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4292 Add mention in Astral quests that attunement is required to see Dim constellations
  config/ftbquests/quests/chapters/astral_sorcery_wip.snbt
Labels: Enhancement

#4294 Fix repair material for Tinker's Plate
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/tconstruct/repair.js
Labels: Enhancement

#4295 Fix crafting recipes for signs and chests
  kubejs/server_scripts/enigmatica/kubejs/base/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/atmospheric/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/enigmatica/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/environmental/shaped.js
  kubejs/server_scripts/enigmatica/kubejs/constants/general.js
Labels: Enhancement

#4296 cleanup stonecutting script, allow otherstone to be cut
  kubejs/server_scripts/enigmatica/kubejs/base/recipetypes/minecraft/stonecutter.js
  kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/create/cutting.js
Labels: Enhancement

#4220 [Expert] Worldshaper Prep
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/alchemy_mastery_shard.png
  kubejs/assets/kubejs/textures/item/alchemy_mastery_token.png
  kubejs/assets/kubejs/textures/item/astronomy_mastery_shard.png
  kubejs/assets/kubejs/textures/item/astronomy_mastery_token.png
  kubejs/assets/kubejs/textures/item/aura_mastery_shard.png
  kubejs/assets/kubejs/textures/item/aura_mastery_token.png
  kubejs/assets/kubejs/textures/item/automation_mastery_shard.png
  kubejs/assets/kubejs/textures/item/automation_mastery_token.png
  kubejs/assets/kubejs/textures/item/battle_mastery_shard.png
  kubejs/assets/kubejs/textures/item/battle_mastery_token.png
  kubejs/assets/kubejs/textures/item/botanical_mastery_shard.png
  kubejs/assets/kubejs/textures/item/botanical_mastery_token.png
  kubejs/assets/kubejs/textures/item/culinary_mastery_shard.png
  kubejs/assets/kubejs/textures/item/culinary_mastery_token.png
  kubejs/assets/kubejs/textures/item/dimensional_mastery_shard.png
  kubejs/assets/kubejs/textures/item/dimensional_mastery_token.png
  kubejs/assets/kubejs/textures/item/energistics_mastery_shard.png
  kubejs/assets/kubejs/textures/item/energistics_mastery_token.png
  kubejs/assets/kubejs/textures/item/engineering_mastery_shard.png
  kubejs/assets/kubejs/textures/item/engineering_mastery_token.png
  kubejs/assets/kubejs/textures/item/excavation_mastery_shard.png
  kubejs/assets/kubejs/textures/item/excavation_mastery_token.png
  kubejs/assets/kubejs/textures/item/laputian_ingot.png
  kubejs/assets/kubejs/textures/item/ritual_mastery_shard.png
  kubejs/assets/kubejs/textures/item/ritual_mastery_token.png
  kubejs/assets/kubejs/textures/item/worldshaper_barrel.png
  kubejs/assets/kubejs/textures/item/worldshaper_cog.png
  kubejs/assets/kubejs/textures/item/worldshaper_handle.png
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/astralsorcery/altar/altar_3_iridescent.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/immersiveengineering/arc_furnace.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/masterful_machinery/enigmatic_tree_of_life.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/mythicbotany/rune_ritual.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/pneumaticcraft/assembly.js
  kubejs/server_scripts/enigmatica/kubejs/expert/tags/items/mythicbotany/ritual_runes.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#4300 [Expert] End game trophy color update
  config/ftbquests/quests/chapters/expert__bragging_rights.snbt
Labels: Development

#4303 [Expert] Ender Crate
  kubejs/client_scripts/constants.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipes/remove.js
  kubejs/server_scripts/enigmatica/kubejs/expert/recipetypes/ars_nouveau/enchanting_apparatus.js
Labels: Development
